### PR TITLE
Robust cgroup path parsing of docker container ID

### LINKED ISSUE #1518: Docker WorkloadAttestor plugin does not work for RHEL
* **Version**: 0.9.0
* **Platform**:  3.10.0-1062.12.1.el7.x86_64,
* **Subsystem**: WorkloadAttestor "docker" (spire-agent)

Docker WorkloadAttestor relies on cgroups to get details about the container selectors.

The code as-written cannot handle extracting the ID out of `docker-<ID>`.scope. It expects the ID to be an entire segment, i.e. `/.../<ID>/...`

Here is an example from docker4desktop (that I think is based on Ubuntu):

```
cat /proc/34089/cgroup
14:name=systemd:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/docker/e46
5ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/system.slice/containerd.service
13:rdma:/
12:pids:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/docker/e465ef604af
b61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/system.slice/containerd.service
11:hugetlb:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9
10:net_prio:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9
9:perf_event:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9
8:net_cls:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9
7:freezer:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9
6:devices:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/docker/e465ef604
afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/system.slice/containerd.service
5:memory:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/docker/e465ef604a
fb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/system.slice/containerd.service
4:blkio:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/docker/e465ef604af
b61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/system.slice/containerd.service
3:cpuacct:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9
2:cpu:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/docker/e465ef604afb6
1d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/system.slice/containerd.service
1:cpuset:/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9
0::/docker/e465ef604afb61d4c3c814f899f668368b0f2568c9b592dabcb4bf980b5597a9/system.slice/containerd
.service
```

vs. RHEL (and I guess CentOS also) system:

```
cat /proc/41223/cgroup
11:hugetlb:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
10:memory:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
9:blkio:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
8:net_prio,net_cls:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
7:perf_event:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
6:cpuset:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
5:pids:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
4:devices:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
3:freezer:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
2:cpuacct,cpu:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
1:name=systemd:/system.slice/docker-41e4ab61d2860b0e1467de0da0a9c6068012761febec402dc04a5a94f32ea867.scope
```
According to the docker workload attestor code here:
https://github.com/spiffe/spire/blob/752d4d4b3cf7ae3f3717f034a99307b8034f0394/pkg/agent/plugin/workloadattestor/docker/docker.go#L31
This will never match RHEL type cgroups.

### PR DESCRIPTION
**Pull request by azdagron**
**Affected functionality** 

Changes the default docker container ID parsing behavior. Current default behavior parses cgroup paths that look like `/docker/<containerid>`. This however does not work in general and the existing (undocumented) options are inflexible enough to handle cgroup paths like those generated by RHEL.

@vbotez prepared a targeted fix with #1522 (thank you!!). It opened up a discussion of the desired semantics, which ended up being quite the departure for the direction the PR started with. This PR 
summarizes the functionality we landed with during that discussion.

**Description of change**

- Uses a simple regex to extract the 64 hex character container ID from any cgroup path with a "docker" whole word prefix somewhere before the ID.
- Replaces the default finder with the above regex
- Still supports the legacy and pattern-based finders
- Does a light refactoring to clean up the mixture of the legacy and pattern based mechanisms and to present one unified "finder" pattern.

**Which issue this PR fixes**
Fixes #1518

### CODE REVIEW

File: pkg/agent/plugin/workloadattestor/docker/docker.go [hunk 1]
```diff
@@ -182,52 +160,115 @@ func (p *Plugin) Configure(ctx context.Context, req *spi.ConfigureRequest) (*spi
...
+	switch {
+	case !hasDockerEntries:
+		// Not a docker workload. Since it is expected that non-docker workloads will call the
+		// workload API, it is fine to return a response without any selectors.
+		return "", nil
+	case containerID == "":
+		// The "finder" found a container ID, but it was blank. This is a
+		// defensive measure against bad matcher patterns and shouldn't
+		// be possible with the default finder.
+		return "", fmt.Errorf("workloadattestor/docker: a pattern matched, but no container id was found")
```
Comment (amartinezfayo) [inline pkg/agent/plugin/workloadattestor/docker/docker.go:230]:
```suggestion
		return "", errors.New("workloadattestor/docker: a pattern matched, but no container id was found")
```

File: pkg/agent/plugin/workloadattestor/docker/docker.go [hunk 2]
```diff
@@ -182,52 +160,115 @@ func (p *Plugin) Configure(ctx context.Context, req *spi.ConfigureRequest) (*spi
...
+// 2) `.+` followed by one or more characters (which will start on a word boundary due to #1)
+// 3) `\b([[:xdigit:]][64])\b` followed by a 64 hex-character container id on word boundary
+//
+// The "docker" prefix and 64-hex character container id can be anywhere in the path. The only
+// requirement is that the docker prefix comes before the id.
+var dockerCGroupRE = regexp.MustCompile(`\bdocker\b.+\b([[:xdigit:]]{64})\b`)
+
+type defaultContainerIDFinder struct{}
+
+func (f *defaultContainerIDFinder) FindContainerID(cgroupPath string) (string, bool) {
```
Comment (amartinezfayo) [inline pkg/agent/plugin/workloadattestor/docker/docker.go:268]: I think that a small comment about this function would be good. We can point that `dockerCGroupRE` is used here and it would be good to explain the meaning of an empty string result and the boolean returned.

**Comment by azdagron** [comment]
Fixed a misspelling in a comment to pass the linter and squashed the commits.
