### PR TITLE
test: `TestSurvivesCARotation` handle empty bundle

### LINKED ISSUE #6416: Flaky test TestSurvivesCARotation
TestSurvivesCARotation sometimes fails in CI.
```
--- FAIL: TestSurvivesCARotation (0.02s)
    manager_test.go:2113: panic: runtime error: invalid memory address or nil pointer dereference
        goroutine 776 [running]:
        runtime/debug.Stack()
        	/opt/hostedtoolcache/go/1.25.3/x64/src/runtime/debug/stack.go:26 +0x5e
        github.com/spiffe/spire/pkg/common/util.(*TaskRunner).StartTasks.func1.1()
        	/home/runner/work/spire/spire/pkg/common/util/task.go:27 +0x46
        panic({0x1aa3c40?, 0x331b3e0?})
        	/opt/hostedtoolcache/go/1.25.3/x64/src/runtime/panic.go:783 +0x132
        github.com/spiffe/spire/pkg/agent/trustbundlesources.(*Bundle).SetSuccessIfRunning(0xc000a06960?)
        	/home/runner/work/spire/spire/pkg/agent/trustbundlesources/bundle.go:85 +0xe
        github.com/spiffe/spire/pkg/agent/manager.(*manager).runSynchronizer(0xc000a06960, {0x216d7c0, 0xc000036d70})
        	/home/runner/work/spire/spire/pkg/agent/manager/manager.go:328 +0x125
        github.com/spiffe/spire/pkg/common/util.(*TaskRunner).StartTasks.func1(0xc000b71a20?)
        	/home/runner/work/spire/spire/pkg/common/util/task.go:31 +0x65
        github.com/spiffe/spire/pkg/common/util.(*TaskRunner).StartTasks.func2()
        	/home/runner/work/spire/spire/pkg/common/util/task.go:37 +0x27
        created by github.com/spiffe/spire/pkg/common/util.(*TaskRunner).StartTasks in goroutine 791
        	/home/runner/work/spire/spire/pkg/common/util/task.go:36 +0x85
        
    manager_test.go:1530: 
        	Error Trace:	/home/runner/work/spire/spire/pkg/agent/manager/manager_test.go:1530
        	Error:      	"[0xc00085f808 0xc000bb0008 0xc000be0008]" should have 2 item(s), but has 3
        	Test:       	TestSurvivesCARotation
FAIL
FAIL	github.com/spiffe/spire/pkg/agent/manager	0.734s
```

### PR DESCRIPTION
**Pull request by rMaxiQp**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

Add Gating on manager's config's `TrustBundleSources` field before setting it to success to avoid nil pointer panic.

**Description of change**

`TrustBundleSources` is not configured, and `m.runSynchronizer()` may trigger a nil pointer panic. If we are lucky and the test exits before the `m.runSynchronizer()`, then the test will pass. Besides the nil pointer panic, I experience multiple CA rotations as well:

```go
// Added some additional logging
--- FAIL: TestSurvivesCARotation (0.04s)
    manager_test.go:1516: create new manager at time: 2025-11-04 21:43:09 -0600 CST // After `newManager()`
    manager_test.go:1525: initialize and run manager at time: 2025-11-04 21:43:09 -0600 CST // After `initializeAndRunManager()`
    manager_test.go:1481: rotate CA at time: 2025-11-04 21:43:09 -0600 CST // Inside `batchNewX509SVIDEntries()`
    manager_test.go:1481: rotate CA at time: 2025-11-04 21:43:10.492416914 -0600 CST
    manager_test.go:1533: 
        	Error Trace:	/home/zq2/remote/spire/pkg/agent/manager/manager_test.go:1533
        	Error:      	"[0xc0035db208 0xc003569208 0xc00368d808]" should have 2 item(s), but has 3
        	Test:       	TestSurvivesCARotation
```

Running the manager before we push the cache update helps to resolve the issue.

**Which issue this PR fixes**

fixes #6416

### CODE REVIEW

File: pkg/agent/manager/manager.go [hunk 1]
```diff
@@ -324,7 +324,7 @@ func (m *manager) runSynchronizer(ctx context.Context) error {
 		}
 
 		err := m.synchronize(ctx)
-		if err == nil {
+		if err == nil && m.c.TrustBundleSources != nil {
```
Comment (sorindumitru) [inline pkg/agent/manager/manager.go]: Interesting find. I guess this means that `m.c.TrustBundleSources` is currently required, with `nil` being invalid. To avoid adding such checks everywhere, could you make that `TrustBundleSources` in the config not a pointer.

Comment (rMaxiQp) [reply pkg/agent/manager/manager.go]: hmm, I tried to cast all current `TrustBundleSources` reference from pointer to struct. Now the test starts to hang, I'll try to understand the root cause.

Comment (rMaxiQp) [reply pkg/agent/manager/manager.go]: EDIT: Please ignore the nonsense below 🙈 , moving `initializeAndRunManager` back to the original position helped.

@sorindumitru That's a strange issue that I didn't experience when using pointers 🤔: 

[`runSynchronizer`](https://github.com/spiffe/spire/blob/main/pkg/agent/manager/manager.go#L317) waits the clock to advance before it calls `synchronize()`:

```go
		select {
		case <-m.clk.After(syncInterval):
		case <-ctx.Done():
			return nil
		}
```
Current clock is a mock clock that's manually advanced: https://github.com/spiffe/spire/blob/main/pkg/agent/manager/manager_test.go#L1526

If the clock advances before the synchronizer waiting for the change, the test would hang. A better approach may be using `SetAfterHook` to advance the time. However, `runSyncSVIDs` is also waiting for clock advancement as well, but waiting for time in milliseconds:
```go
[2025-11-06 14:08:01 -0600 CST] runSyncSVIDs: clk.After: 489.796926ms 
[2025-11-06 14:08:07 -0600 CST] runSyncSVIDs: clk.After: 502.365261ms 
[2025-11-06 14:08:11.5 -0600 CST] runSyncSVIDs: clk.After: 540.991324ms 
```
differs than the runSynchronizer:
```go
[2025-11-06 14:08:02.5 -0600 CST] runSynchronizer: syncInterval: 1.442233945s
```

Thus, alternative here would be advance the clock once we receive a `clk.After()` that's close to the syncInterval. Please let me know if I'm missing out anything here. If this change makes sense to you, I can try to implement this fix.

Comment (sorindumitru) [reply pkg/agent/manager/manager.go]: The mock clock we're using has a `WaitAfter` method for things like this. It's not perfect, it just waits for the first call to `After`, but it should help in this case. It's a common source of issues with our tests.

Comment (rMaxiQp) [reply pkg/agent/manager/manager.go]: Thank you for the context! With a further investigation, I realized that's the second `notify` wasn't triggered was the actual cause. Moving `initializeAndRunManager` back to the original position helped to resolve this issue...
