### PR TITLE
golangci-lint: upgrade to v2 & fix flakey test

### LINKED ISSUE #5774: Flaky test - TestAttestAgent/rate_limit_fails
```
--- FAIL: TestAttestAgent (0.33s)
    --- FAIL: TestAttestAgent/rate_limit_fails (0.01s)
        service_test.go:3436: 
            	Error Trace:	/home/runner/work/spire/spire/pkg/server/api/agent/v1/service_test.go:3436
            	            				/home/runner/work/spire/spire/pkg/server/api/agent/v1/service_test.go:3175
            	Error:      	Received unexpected error:
            	            	EOF
            	Test:       	TestAttestAgent/rate_limit_fails
        server.go:123: Gracefully stopping gRPC server
        server.go:125: Server stopped
        server.go:127: Server serve returned <nil>
        server.go:119: Waiting for handlers to drain
        server.go:121: Handlers drained
FAIL
FAIL	github.com/spiffe/spire/pkg/server/api/agent/v1	0.919s
```

https://github.com/spiffe/spire/actions/runs/12777880767/job/35619626996?pr=5762

### PR DESCRIPTION
**Pull request by c4rlo**
- Upgrade `golangci-lint` to the latest version, v2.1.6.
- Migrate to new config file format as required with v2.
- Run `golangci-lint` via `go run` not `go tool`; the docs [explicitly recommend against the latter](https://golangci-lint.run/welcome/install/#install-from-sources), and it was needlessly polluting our `go.mod` file. (The docs primarily recommend installing from a binary distribution, but I wasn't sure if such a change would be desirable.)
- With the new way, the `golangci-lint` version is maintained in `.spire-tool-versions`, consistent with other similar tools.
- While we're at it, enable a few more linters/checks.
- Address all new linter complaints.
- Simplify some error return patterns (found by grepping, not via a linter).
- Fix flakey `TestAttestAgent` test (hopefully), by not failing if the client receives `io.EOF` from the `Send()` method of the stream. Fixes #5774.

### CODE REVIEW

File: pkg/agent/trustbundlesources/bundle_test.go [hunk 1]
```diff
@@ -86,7 +86,7 @@ func TestSetupTrustBundle(t *testing.T) {
 		t.Run(testCase.msg, func(t *testing.T) {
 			var err error
 			var ac agent.Config
-			var c Config = Config{
+			var c = Config{
```
Comment (faisal-memon) [inline pkg/agent/trustbundlesources/bundle_test.go:89]:
```suggestion
			c := Config{
```

File: pkg/server/endpoints/authorized_entryfetcher_attested_nodes_test.go [hunk 2]
```diff
@@ -215,7 +215,7 @@ func TestLoadNodeCache(t *testing.T) {
 			cacheStats = attestedNodes.cache.Stats()
 			require.Equal(t, 0, cacheStats.AgentsByID, "clearing all expected agent ids didn't clear cache")
 
-			var lastMetrics map[string]int = make(map[string]int)
+			var lastMetrics = make(map[string]int)
```
Comment (faisal-memon) [inline pkg/server/endpoints/authorized_entryfetcher_attested_nodes_test.go:218]:
```suggestion
			lastMetrics := make(map[string]int)
```

File: pkg/server/endpoints/authorized_entryfetcher_registration_entries_test.go [hunk 3]
```diff
@@ -395,7 +395,7 @@ func TestLoadEntryCache(t *testing.T) {
 			require.Equal(t, 0, cacheStats.EntriesByEntryID,
 				"clearing all expected entry ids didn't clear cache")
 
-			var lastMetrics map[string]int = make(map[string]int)
+			var lastMetrics = make(map[string]int)
```
Comment (faisal-memon) [inline pkg/server/endpoints/authorized_entryfetcher_registration_entries_test.go:398]:
```suggestion
			lastMetrics := make(map[string]int)
```

File: pkg/agent/manager/manager_test.go [hunk 4]
```diff
@@ -468,10 +468,8 @@ func TestSVIDRotation(t *testing.T) {
 
 	// Loop until we detect an SVID rotation was called in separate process
 	util.RunWithTimeout(t, time.Minute, func() {
-		for {
-			if wasRotHookCalled() {
-				break
-			}
+		for !wasRotHookCalled() {
+
```
Comment (faisal-memon) [inline pkg/agent/manager/manager_test.go:472]: Would a require.Eventually() work better here?

**Comment by rturner3** [comment]
Hi @c4rlo, it looks like there are now some merge conflicts with this PR. Would you mind addressing those? Then we can take another look here. Thanks!

**Comment by c4rlo** [comment]
Merge conflicts addressed.

**Review by MarcosDY — APPROVED** [review]
