### PR TITLE
Fix to properly handle disabled plugins

### LINKED ISSUE #335: Setting a plugin to `enabled = false` causes SIGSEV
Testing the new (and awesome) unified config, I found that setting plugins to `enabled = false` causes a SIGSEV. This is true of both the Spire Agent and Spire Server.

For example:
```
    NodeAttestor "join_token" {
        plugin_cmd = "plugin/agent/nodeattestor-jointoken/nodeattestor-jointoken"
        plugin_checksum = ""
        enabled = false
        plugin_data {
            trust_domain = "example.org"
        }
    }
```

Causes the following error on `spire-agent run`:
```
DEBU[0000] Configuring NodeAttestor plugin: join_token   subsystem_name=catalog
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x87684c]

goroutine 1 [running]:
github.com/spiffe/spire/pkg/common/catalog.(*catalog).configurePlugins(0xc420144940, 0x0, 0x0)
        /root/go/src/github.com/spiffe/spire/pkg/common/catalog/catalog.go:217 +0x19c
github.com/spiffe/spire/pkg/common/catalog.(*catalog).Run(0xc420144940, 0x0, 0x0)
        /root/go/src/github.com/spiffe/spire/pkg/common/catalog/catalog.go:86 +0x1da
github.com/spiffe/spire/pkg/agent/catalog.(*catalog).Run(0xc4201478c0, 0x0, 0x0)
        /root/go/src/github.com/spiffe/spire/pkg/agent/catalog/catalog.go:71 +0x85
github.com/spiffe/spire/pkg/agent.(*Agent).initPlugins(0xc420124120, 0xc420135c40, 0x410d78)
        /root/go/src/github.com/spiffe/spire/pkg/agent/agent.go:165 +0x34
```

Commenting out the offending config block removes the error, spire-agent starts normally.

* **Version**: Built from d55a1ed8112f37154b638b889923eb1de508c6af
* **Platform**: Linux attestor-dev-machine2 4.13.0-1002-gcp #5-Ubuntu SMP Tue Dec 5 13:20:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: spire-server, spire-agent

### PR DESCRIPTION
**Pull request by amartinezfayo**
- Fix plugin catalog functions to properly handle disabled plugins.
- Have catalog tests with plugins not enabled.

This fixes #335.

### CODE REVIEW

File: pkg/common/catalog/catalog.go [hunk 1]
```diff
@@ -209,6 +209,11 @@ func (c *catalog) startPlugins() error {
 
 func (c *catalog) configurePlugins() error {
 	for _, p := range c.plugins {
+		if !p.Config.Enabled {
+			c.l.Infof("%s plugin %s is disabled and will not be configured", p.Config.PluginType, p.Config.PluginName)
```
Comment (evan2645) [inline pkg/common/catalog/catalog.go]: Looks like for each disabled plugin, we'll receive several log lines?

I think `debug` level makes sense here. In the future, when we have statically-linked plugins, disabled will probably be the default state

Comment (amartinezfayo) [reply pkg/common/catalog/catalog.go]: Right, I'll change it to `debug` level. Thanks!

**Comment by ajessup** [comment]
Verified fixed. Thanks @amartinezfayo!
