### PR TITLE
Fixes #3130: Adds orhpaned record pruning on Server startup

### LINKED ISSUE #3130: Remove orphaned entry-related database rows
The bug reported in #3126 caused dns_names rows to be orphaned when entries were deleted. There was a similar bug existed previously for selectors (#1191). Due to these bugs, its possible that existing deployments have accumulated large amounts of database cruft that could be impacting query performance, particularly in entry list operations which involve many joins with the impacted tables.

We should consider adding some code that removes the orphaned rows on startup. If we get it out in the 1.3.X timeline, then we can probably remove it in 1.5.0, since deployments moving through our supported upgrade path would execute the cleanup code at least once (either as part of deploying 1.3.X or 1.4.X release that contains the removal code).

### PR DESCRIPTION
**Pull request by dennisgove**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
During SPIRE Server sqlstore configuration (happens at startup), a pruning step will be executed which will remove db records which have been orphaned.

**Description of change**
This change adds a new method which will be called on every SPIRE Server startup in order to prune orphaned database records.  

**Which issue this PR fixes**
Fixes #3130

### CODE REVIEW

File: pkg/server/datastore/sqlstore/sqlstore.go [hunk 1]
```diff
@@ -524,6 +525,12 @@ func (ds *Plugin) Configure(hclConfiguration string) error {
 		return err
 	}
 
+	if err := ds.withWriteTx(context.Background(), func(tx *gorm.DB) (err error) {
```
Comment (azdagron) [inline pkg/server/datastore/sqlstore/sqlstore.go:528]: We should change Configure to take a context and pass that here (will require threading through the context from the server catalog code).

**Review by azdagron — COMMENTED** [review]
Thanks @dennisgove ! This looks great. I just have one comment on the context used the the transaction that should be trivially addressable.

File: pkg/server/datastore/sqlstore/sqlstore.go [hunk 2]
```diff
@@ -3800,3 +3807,30 @@ func lookupSimilarEntry(ctx context.Context, db *sqlDB, tx *gorm.DB, entry *comm
...
+func pruneOrphanedRecords(tx *gorm.DB, logger logrus.FieldLogger) error {
+	// Delete selectors which were left behind during registered_entry deletion.
+	// The issue allowing orphaned selector records was fixed in #1191
+	// TODO: remove in 1.5.0 (see #3131)
+	if res := tx.Exec("DELETE FROM selectors WHERE registered_entry_id NOT IN (SELECT id FROM registered_entries)"); res.Error != nil {
+		return sqlError.Wrap(res.Error)
+	} else if (res.RowsAffected > 0) {
+		logger.WithFields(logrus.Fields{
+			telemetry.Count: res.RowsAffected,
+		}).Info("Pruned orphaned selectors")
```
Comment (azdagron) [inline pkg/server/datastore/sqlstore/sqlstore.go:3821]: :heart:

File: pkg/server/datastore/sqlstore/sqlstore.go [hunk 3]
```diff
@@ -3800,3 +3807,30 @@ func lookupSimilarEntry(ctx context.Context, db *sqlDB, tx *gorm.DB, entry *comm
...
 }
+
+// pruneOrphanedRecords will delete from the database any table rows which have become orphaned.
+func pruneOrphanedRecords(tx *gorm.DB, logger logrus.FieldLogger) error {
+	// Delete selectors which were left behind during registered_entry deletion.
+	// The issue allowing orphaned selector records was fixed in #1191
+	// TODO: remove in 1.5.0 (see #3131)
+	if res := tx.Exec("DELETE FROM selectors WHERE registered_entry_id NOT IN (SELECT id FROM registered_entries)"); res.Error != nil {
+		return sqlError.Wrap(res.Error)
+	} else if (res.RowsAffected > 0) {
```
Comment (azdagron) [inline pkg/server/datastore/sqlstore/sqlstore.go:3818]: nit: boolean condition does not require parenthesis

File: pkg/server/datastore/sqlstore/sqlstore.go (hunk 2 above)
Comment (azdagron) [inline pkg/server/datastore/sqlstore/sqlstore.go:3821]: If there is just one field, this can be consolidated:
```suggestion
		logger.WithField(telemetry.Count, res.RowsAffected).Info("Pruned orphaned selectors")
```

File: pkg/server/datastore/sqlstore/sqlstore.go [hunk 4]
```diff
@@ -3800,3 +3807,30 @@ func lookupSimilarEntry(ctx context.Context, db *sqlDB, tx *gorm.DB, entry *comm
...
+
+	// Delete dns_names which were left behind during registered_entry deletion.
+	// The issue allowing orphaned dns_name records was reported in #3126 and fixed in #3127
+	// TODO: remove in 1.5.0 (see #3131)
+	if res := tx.Exec("DELETE FROM dns_names WHERE registered_entry_id NOT IN (SELECT id FROM registered_entries)"); res.Error != nil {
+		return sqlError.Wrap(res.Error)
+	} else if (res.RowsAffected > 0) {
+		logger.WithFields(logrus.Fields{
+			telemetry.Count: res.RowsAffected,
+		}).Info("Pruned orphaned dns_names")
```
Comment (azdagron) [inline pkg/server/datastore/sqlstore/sqlstore.go:3832]: nitpick: If there is just one field, this can be consolidated:
```suggestion
		logger.WithField(telemetry.Count, res.RowsAffected).Info("Pruned orphaned dns_names")
```

**Review by azdagron — APPROVED** [review]
Awesome. Thanks for this, @dennisgove!
