### PR TITLE
Bring down the agent when it needs to re-attest

### LINKED ISSUE #1644: Agents should re-attest if evicted
Following on from #1257,
If a SPIRE agent has previously attested and still has a valid SVID, but then gets evicted, it will fail all subsequent calls to the SPIRE Server due to having an SVID not recognized by the Server. When the SVID's validity finally runs out, the agent will crash and finally re-attest. Workaround is to delete the agent's `.data` contents, which is not maintainable at scale.
Given the agent will eventually attempt attestation anyway, it should know it has been evicted and re-attest automatically rather than waiting for an arbitrary countdown of its own SVID validity.

### PR DESCRIPTION
**Pull request by kunzimariano**
Signed-off-by: Mariano Kunzi <kunzi.mariano@gmail.com>

**Affected functionality**

Agent shutting down when meeting conditions that require re-attestation.

**Description of change**

When making calls to the server, and getting `PermissionDenied`, and the reason being one of the next `[PermissionDeniedDetails_AGENT_EXPIRED, PermissionDeniedDetails_AGENT_NOT_ACTIVE, PermissionDeniedDetails_AGENT_NOT_ATTESTED]`, the agent will shutdown and delete the SVID in order to execute a re attestation.

**Which issue this PR fixes**

fixes #1644

### CODE REVIEW

File: pkg/agent/manager/manager.go [hunk 1]
```diff
@@ -97,12 +98,19 @@ func (m *manager) Initialize(ctx context.Context) error {
...
-		return fmt.Errorf("fail to store private key: %v", err)
+		return fmt.Errorf("failed to store private key: %v", err)
 	}
 
 	m.backoff = backoff.NewBackoff(m.clk, m.c.SyncInterval)
 
-	return m.synchronize(ctx)
+	err = m.synchronize(ctx)
+	if nodeutil.IsShutdownError(err) {
+		m.c.Log.WithError(err).Error("Failed to synchronize: removing SVID")
```
Comment (azdagron) [inline pkg/agent/manager/manager.go:108]:
```suggestion
		m.c.Log.WithError(err).Error("Agent needs to re-attest: removing SVID and shutting down")
```

File: pkg/agent/manager/manager.go [hunk 2]
```diff
@@ -113,13 +121,23 @@ func (m *manager) Run(ctx context.Context) error {
 		m.runSVIDObserver,
 		m.runBundleObserver,
 		m.svid.Run)
-	if err != nil && err != context.Canceled {
-		m.c.Log.WithError(err).Error("cache manager crashed")
+
+	switch {
```
Comment (azdagron) [inline pkg/agent/manager/manager.go:125]: This switch seems a little unwieldy. How would you feel about the following?
```suggestion
	switch {
	case err == nil || err == context.Canceled:
		m.c.Log.Info("Cache manager stopped")
		return nil
	case shouldAgentReattest(err):
		m.c.Log.WithError(err).Warn("Agent needs to re-attest; removing SVID and shutting down")
		... Rest of the delete logic
		return err
	default:
		m.c.Log.WithError(err).Error("cache manager crashed")
		return err
	}
```

File: pkg/agent/client/client.go [hunk 3]
```diff
@@ -311,7 +311,7 @@ func (c *client) fetchEntries(ctx context.Context) ([]*types.Entry, error) {
 	if err != nil {
 		c.release(connection)
 		c.c.Log.WithError(err).Error("Failed to fetch authorized entries")
-		return nil, fmt.Errorf("failed to fetch authorized entries: %v", err)
+		return nil, err
```
Comment (azdagron) [inline pkg/agent/client/client.go:314]: Can keep this "embellishment" if we wrap the error and then `isShutdownError` changes to unwrap?
```suggestion
		return nil, fmt.Errorf("failed to fetch authorized entries: %w", err)
```

See https://golang.org/pkg/errors/#Unwrap

It would probably be good to wrap all of the errors (via `%w`) on all of the errors coming out of the client so we can react to status messages coming out of other authenticated RPCs (i.e. BatchNewX509SVID)

File: pkg/agent/manager/manager.go [hunk 4]
```diff
@@ -97,12 +98,19 @@ func (m *manager) Initialize(ctx context.Context) error {
...
 
 	m.backoff = backoff.NewBackoff(m.clk, m.c.SyncInterval)
 
-	return m.synchronize(ctx)
+	err = m.synchronize(ctx)
+	if nodeutil.IsShutdownError(err) {
+		m.c.Log.WithError(err).Error("Failed to synchronize: removing SVID")
+		if deleteErr := DeleteSVID(m.svidCachePath); deleteErr != nil {
+			m.c.Log.WithError(deleteErr).Error("Failed to remove SVID")
+		}
```
Comment (azdagron) [inline pkg/agent/manager/manager.go:111]: we're doing this in a few spots. can this be moved to a shared function? (i.e. m.deleteSVID)

File: pkg/common/nodeutil/node.go [hunk 5]
```diff
@@ -2,10 +2,31 @@ package nodeutil
...
+		return false
+	}
+
+	for _, errDetail := range errStatus.Details() {
+		errReason, _ := errDetail.(*types.PermissionDeniedDetails)
+		if errReason.Reason == types.PermissionDeniedDetails_AGENT_EXPIRED ||
+			errReason.Reason == types.PermissionDeniedDetails_AGENT_NOT_ACTIVE ||
+			errReason.Reason == types.PermissionDeniedDetails_AGENT_NOT_ATTESTED {
+			return true
+		}
```
[the remark this answers is not in the document]
Comment (kunzimariano) [reply pkg/common/nodeutil/node.go:29]: 🤦🏼 You are absolutely right!

File: pkg/common/nodeutil/node.go [hunk 6]
```diff
@@ -2,10 +2,31 @@ package nodeutil
...
 )
 
 // IsAgentBanned determines if a given attested node is banned or not.
 // An agent is considered as "banned" if its X509 SVID serial number is empty.
 func IsAgentBanned(node *common.AttestedNode) bool {
 	return node.CertSerialNumber == ""
 }
+
+// IsShutdownError returns true if the Server returned an error worth rebooting the Agent
+func IsShutdownError(err error) bool {
```
[the remark this answers is not in the document]
Comment (kunzimariano) [reply pkg/common/nodeutil/node.go:17]: 💯

File: pkg/agent/manager/manager.go (hunk 2 above)
Comment (kunzimariano) [reply pkg/agent/manager/manager.go:125]: Thanks for that snippet!

File: pkg/agent/client/client.go (hunk 3 above)
Comment (kunzimariano) [reply pkg/agent/client/client.go]: I also wrapped `BatchNewX509SVID` in the last commit. What do you think about `NewJWTSVID`, `RenewAgent` and `GetFederatedBundle`? The first one it's not being wrapped, while the other two are not being embellished.

Comment (azdagron) [reply pkg/agent/client/client.go]: As long as each error is either wrapped or not embellished, we are ok. If you want to update those other methods to wrap and embellish the error message, I'd be fine with that.

**Review by azdagron — APPROVED** [review]
This seems good. If you want to update those other API calls to wrap and embellish the gRPC status coming back, that would be good too, but otherwise that can be tackled separately.

**Comment by kunzimariano** [comment]
I added a new commit that embellishes and wraps the remaining errors. I had to amend the last commit you saw, it had the wrong user and sign-off. Sorry if that makes the reviewing process more difficult.

**Review by azdagron — APPROVED** [review]
\o/ Thanks for your patience on this @kunzimariano !
