### PR TITLE
Fixed workload attestation when using AWS Node Resolver

### LINKED ISSUE #326: Workloads fail to receive identity when using AWS Node Resolver plugin
Workloads fail to be attested by an agent running in AWS using AWS Node Resolver plugin.

* **Version**: https://github.com/spiffe/spire/commit/44db65fe992d0089c3f4fd00f3340f4862040965
* **Platform**: Ubuntu 16
* **Subsystem**: Spire Agent

### PR DESCRIPTION
**Pull request by paul-argeniss**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [X] Documentation updated?

**Affected functionality**
Workloads fail to receive identity when using AWS Node Resolver plugin.

**Description of change**
- Changed fetchRegistrationEntries so that it looks for all possible combinations of selectors.
- Changed Cache Manager to identity the registration entry with the magic parentSpiffeID (feel free to suggest a better name) that identities the node entry and keep track of its spiffeID.

**Which issue this PR fixes**
Fixes #326

### CODE REVIEW

File: pkg/agent/cache/manager.go [hunk 1]
```diff
@@ -76,6 +78,8 @@ type manager struct {
 	once             sync.Once
 	doneCh           chan struct{}
 	pipelineCnt      int32
+	aliasSPIFFEID    string
+	magicSPIFFEID    string
```
Comment (evan2645) [inline pkg/agent/cache/manager.go]: nit: `serverSPIFFEID`

Comment (evan2645) [reply pkg/agent/cache/manager.go]: These should probably be URL type instead of string

File: pkg/agent/cache/manager.go [hunk 2]
```diff
@@ -153,11 +158,13 @@ func (m *manager) Init() {
...
 						svid = m.spiffeIdEntryMap[parentId].SVID
 						key = m.spiffeIdEntryMap[parentId].PrivateKey
-					}
-					if parentId == m.baseSPIFFEID {
+					} else if parentId == m.baseSPIFFEID || parentId == m.magicSPIFFEID {
 						entry := m.getBaseSVIDEntry()
 						svid = entry.svid
 						key = entry.key
+					} else {
+						m.log.Debug("Unknown parent ", parentId, "... ignoring")
```
Comment (evan2645) [inline pkg/agent/cache/manager.go]: An info or warn level may be more appropriate, since reaching this point means something is probably wrong. Also, you can use `Infof` or `Warnf` for proper string formatting

File: pkg/server/node.go [hunk 3]
```diff
@@ -188,14 +189,16 @@ func (s *nodeServer) fetchRegistrationEntries(selectors []*common.Selector, spif
 	var entries []*common.RegistrationEntry
 
 	///lookup Registration Entries for resolved selectors
-	req := &datastore.ListSelectorEntriesRequest{Selectors: selectors}
-	listSelectorResponse, err := dataStore.ListMatchingEntries(req)
-	if err != nil {
-		return nil, err
-	}
+	for combination := range selector.PowerSet(selector.NewSet(selectors)) {
```
Comment (evan2645) [inline pkg/server/node.go]: Tests to capture this updated logic would be awesome... I feel we'll probably refactor this handler in the near future

File: functional/Makefile [hunk 4]
```diff
@@ -13,7 +13,7 @@ all: clean build server agent test
 build:
 	docker-compose build runner
 	docker-compose up -d runner
-	docker-compose exec runner bash -c 'mkdir -p $(DOCKER_SPIRE) && cp -R /spire-orig/* $(DOCKER_SPIRE)'
+	docker-compose exec runner bash -c 'mkdir -p $(DOCKER_SPIRE) $(DOCKER_SPIRE)/.data && cp -R /spire-orig/* $(DOCKER_SPIRE)'
```
[the remark this answers is not in the document]
Comment (paul-argeniss) [reply functional/Makefile]: Good catch.

File: pkg/server/node.go (hunk 3 above)
Comment (paul-argeniss) [reply pkg/server/node.go]: Added test.

File: pkg/agent/cache/manager.go (hunk 1 above)
Comment (paul-argeniss) [reply pkg/agent/cache/manager.go]: `serverSPIFFEID` already exists here and it's a string, that's why I'm also using strings here. I can change it if you feel strongly about it.

Comment (evan2645) [reply pkg/agent/cache/manager.go]: it's ok, we can fix it later. we'll probably need to refactor all this anyways once the workload api updates land.
