### PR TITLE
Registrar wait up to 60 seconds for SPIRE Server to start

### LINKED ISSUE #2872: k8s-workload-registrar container restarts because spire-server's socket is not ready
* **Version**: 1.0.1, 1.1.0 and 1.2.0
* **Platform**: Linux 5.13.0-30-generic - 20.04.1-Ubuntu SMP x86_64
* **Subsystem**: server

I used this [configuration](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/spire) for my tests.

In case I run it first time on a fresh cluster there is no container restart because while spire-server container starts, kubelet is just downloading k8s-workload-registrar image. Therefore spire-server has some time to start its UDS server and k8s-workload-registrar will be able to connect.

To reproduce the restart, delete spire related resouces by the below commands:
```
kubectl delete validatingwebhookconfiguration k8s-workload-registrar
kubectl delete crd spiffeids.spiffeid.spiffe.io
kubectl delete ns spire
```

Then deploy it again: `kubectl apply -k spire`

Now the restart of the k8s-workload-registrar container can be observed:
```
$ kubectl get pods -n spire`
NAME                READY   STATUS    RESTARTS   AGE
spire-agent-6prkf   1/1     Running   0          42s
spire-agent-9xpqk   1/1     Running   0          42s
spire-server-0      2/2     Running   1          42s
```
In the attached logs it can be seen that the UDS server is just starting in the same second when k8s-workload-registrar wants to connect to the socket which is not ready yet. Which causes the container restart.
[k8s-workload-registrar-err.log](https://github.com/spiffe/spire/files/8315021/k8s-workload-registrar-err.log)
[spire-server-err.log](https://github.com/spiffe/spire/files/8315024/spire-server-err.log)

I applied the below temporary workaround in the spire-server container specification:
```
lifecycle:
  postStart:
    exec:
      command: ["sleep", "2"]
```

According to the logs the k8s-workload-registrar container starts 2 seconds after UDS server started and the connection is successful, there are no restarts.

### PR DESCRIPTION
**Pull request by faisal-memon**
Signed-off-by: Faisal Memon <fymemon@yahoo.com>

**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
k8s-workload-registrar

**Description of change**
Has the k8s-workload-registrar wait up to 60 seconds for the spire server to be up before restarting. This is to support spire-server with large configs that takes a while to start up.

**Which issue this PR fixes**
fixes #2872

### CODE REVIEW

File: support/k8s/k8s-workload-registrar/mode-crd/webhook/webhook_svid.go [hunk 1]
```diff
@@ -91,7 +92,13 @@ func (e *SVID) MintSVID(ctx context.Context, key crypto.Signer) (err error) {
...
 	// Mint new SVID
 	var resp *svidv1.MintX509SVIDResponse
-	err = retry.OnError(retry.DefaultBackoff, e.mintSVIDRetry, func() (err error) {
+	backoff := wait.Backoff{
+		Steps:    11,
+		Duration: 15 * time.Millisecond,
+		Factor:   2.0,
+		Jitter:   0.1,
+	}
+	err = retry.OnError(backoff, e.mintSVIDRetry, func() (err error) {
```
Comment (azdagron) [inline support/k8s/k8s-workload-registrar/mode-crd/webhook/webhook_svid.go:101]: How long was the backoff for previous to this change? One minute feels like a long time to detect a misconfiguration...

Comment (faisal-memon) [reply support/k8s/k8s-workload-registrar/mode-crd/webhook/webhook_svid.go:101]: about 1.5 seconds. On slack someone mentioned needing up to a minute because they had a log of OPA rules to process, so thats where the 1 minute number comes from. It is a bit long, i agree.

**Comment by azdagron** [comment]
For posterity, we discussed this PR during a contributor sync up and the outcome was that 1 minute was too long. The consensus was to wait five seconds and that logging should be added so that it is clear attempts are being made.

**Comment by faisal-memon** [comment]
> For posterity, we discussed this PR during a contributor sync up and the outcome was that 1 minute was too long. The consensus was to wait five seconds and that logging should be added so that it is clear attempts are being made.

Updated with a 5 second timeout and logs. I also added a hidden configurable to increase the timeout to cover the use cases where it takes spire server a long time to start.

**Comment by azdagron** [comment]
Thanks for updating, @faisal-memon!

>  I also added a hidden configurable

It has been the experience on this project, that hidden (i.e. undocumented) configurables always become documented over time. In my opinion, I think we should either hard code the number of retries or we document the configurable. Curious what the other @spiffe/spire-maintainers think.

In terms of the configurable, # of attempts is hard for somebody to guess unless they understand how the backoff works. I think it would be more ergonomic to configure the max duration to wait and configure the backoff accordingly.

**Comment by faisal-memon** [comment]
> Thanks for updating, @faisal-memon!
> 
> > I also added a hidden configurable
> 
> It has been the experience on this project, that hidden (i.e. undocumented) configurables always become documented over time. In my opinion, I think we should either hard code the number of retries or we document the configurable. Curious what the other @spiffe/spire-maintainers think.
> 
> In terms of the configurable, # of attempts is hard for somebody to guess unless they understand how the backoff works. I think it would be more ergonomic to configure the max duration to wait and configure the backoff accordingly.

makes sense, ill remove the configurable.

**Review by azdagron — APPROVED** [review]
\o/

**Comment by edwarnicke** [comment]
@azdagron Any idea when this will be in a release version of Spire?

**Comment by azdagron** [comment]
Great timing! The commit for the 1.3.0 release is likely getting picked today (we have one outstanding PR), which means 1.3.0 is expected to be released one week from today, which is April 10th.
