### PR TITLE
Fail to start server/agent on unknown config

### LINKED ISSUE #1101: Server and agent should detect unknown config options
The current behavior of both server and agent is to ignore configurables that we don't know about (i.e. aren't defined in our respective config structs). This causes some friction for a variety of misconfiguration cases:
* A typo in config key name
* Misplaced directives (e.g. a plugin defined in the server configuration block)
* Attempting to use a new feature against an old version

In these cases, SPIRE can boot normally and does not give any indication that something is wrong. Users are then surprised when they don't see the behavior they expect.

Both server and agent should detect if unknown configuration parameters are set, and either warn or refuse to start. The catalog and telemetry subsystems should be updated to have this behavior as well for their respective config blocks. I think the former may already have some of this behavior.

Correctness of plugin_data will need to be handled separately and is out of scope for this issue.

### LINKED ISSUE #1432: Detection of invalid config option should be fatal
SPIRE Server and Agent currently detect unknown config options and log a warning when they're encountered. We introduced the warning as a compatibility measure, with the ideal behavior being to not start at all. The warning was added in 0.9.1.

This issue is to upgrade the warning to an error, and instead of proceeding to boot the server or the agent, exit with a non-zero code.

Blocked on 0.11.0-dev

### PR DESCRIPTION
**Pull request by azdagron**
Also allows for consumers who are extending the CLI to opt-out of the unknown configuration check.

Fixes #1101, fixes #1432

### CODE REVIEW

File: cmd/spire-agent/cli/run/run.go [hunk 1]
```diff
@@ -441,51 +443,61 @@ func validateConfig(c *Config) error {
 	return nil
 }
 
-func warnOnUnknownConfig(c *Config, l logrus.FieldLogger) {
+func checkForUnknownConfig(c *Config, l logrus.FieldLogger) (err error) {
+	detectedUnknown := func(section string, keys []string) {
+		l.WithFields(logrus.Fields{
+			"section": section,
+			"keys":    strings.Join(keys, ","),
+		}).Error("Unknown configuration detected")
```
Comment (amartinezfayo) [inline cmd/spire-agent/cli/run/run.go:451]: Since this effectively terminates the program, we may use the fatal level?

```suggestion
		}).Fatal("Unknown configuration detected")
```

File: cmd/spire-server/cli/run/run.go [hunk 2]
```diff
@@ -592,48 +587,56 @@ func warnOnDeprecatedConfig(c *Config, l logrus.FieldLogger) {
 	}
 }
 
-func warnOnUnknownConfig(c *Config, l logrus.FieldLogger) {
+func checkForUnknownConfig(c *Config, l logrus.FieldLogger) (err error) {
+	detectedUnknown := func(section string, keys []string) {
+		l.WithFields(logrus.Fields{
+			"section": section,
+			"keys":    strings.Join(keys, ","),
+		}).Error("Unknown configuration detected")
```
Comment (amartinezfayo) [inline cmd/spire-server/cli/run/run.go:595]: Since this effectively terminates the program, we may use the fatal level?

```suggestion
		}).Fatal("Unknown configuration detected")
```

File: test/spiretest/logs.go [hunk 3]
```diff
@@ -24,6 +24,16 @@ func AssertLogs(t *testing.T, entries []*logrus.Entry, expected []LogEntry) {
 	assert.Equal(t, expected, convertLogEntries(entries), "unexpected logs")
 }
 
+func AssertLogsAnyOrder(t *testing.T, entries []*logrus.Entry, expected []LogEntry) {
```
Comment (amartinezfayo) [inline test/spiretest/logs.go:27]: 💯

File: cmd/spire-agent/cli/run/run.go (hunk 1 above)
Comment (azdagron) [reply cmd/spire-agent/cli/run/run.go]: Sure! Updated.

File: cmd/spire-server/cli/run/run.go (hunk 2 above)
Comment (azdagron) [reply cmd/spire-server/cli/run/run.go]: Sure! Updated.

**Comment by azdagron** [comment]
Actually, we don't want Fatal. It calls os.Exit(). I'm going to change it back to Error level. I'll also squash and rebase.
