### PR TITLE
Prevent agent from storing an invalid key on failed SVID rotation

### LINKED ISSUE #613: Agent has a window during which it cannot recover from a restart
The agent keymanager can generate a new key internally and return it, however when rotating the key, there is no way to persist the new key if and only if the agent's SVID was successfully renewed. The result is that if the agent restarts between the time it generates a new key and the time that the server fulfills its rotation request, the cert and key will no longer match.

Refactor agent's key manager interface to make rotation graceful and recoverable

### PR DESCRIPTION
**Pull request by APTy**
This separates key generation from key storage in the keymanager plugin, which enables the application to handle cases when SVID renewal fails, and choose not to store the invalid private key (since it doesn't correspond to a valid SVID).

Fixes #613

### CODE REVIEW

File: pkg/agent/svid/rotator.go [hunk 1]
```diff
@@ -120,6 +120,18 @@ func (r *rotator) rotateSVID(ctx context.Context) (err error) {
...
+	mgrs := r.c.Catalog.KeyManagers()
+	if len(mgrs) > 1 {
+		return errors.New("more than one key manager configured")
+	}
+	keyBytes, err := x509.MarshalECPrivateKey(key)
+	if err != nil {
+		return err
+	}
+	if _, err := mgrs[0].StorePrivateKey(ctx, &keymanager.StorePrivateKeyRequest{PrivateKey: keyBytes}); err != nil {
+		return fmt.Errorf("generate key pair: %v", err)
```
Comment (evan2645) [inline pkg/agent/svid/rotator.go]: This will break compatibility for folks who are running key managers built against the old interface. I think we should log a warning here instead of completely bailing out. Perhaps something like this?
```suggestion
		r.c.Log.Errorf("could not store new agent key pair: %v", err)
		r.c.Log.Warn("Error encountered while storing new agent key pair. Is your KeyManager plugin is up-to-date?")
```

I think ultimately, we should move this whole keymanager interface to something closer to (or matching?) the server keymanager interface. Exposing the private key is definitely a smell, and is not strictly required. I have opened #670 to track this, it will be a big breaking change, we can tackle it for 0.8.

File: go.sum [hunk 2]
```diff
@@ -23,6 +23,7 @@ github.com/dgrijalva/jwt-go v3.2.0+incompatible h1:7qlOGliEKZXTDg6OTjfoBKDXWrumC
 github.com/dgrijalva/jwt-go v3.2.0+incompatible/go.mod h1:E3ru+11k8xSBh+hMPgOLZmtrrCbhqsmaPHjLKYnJCaQ=
 github.com/dimchansky/utfbom v1.0.0 h1:fGC2kkf4qOoKqZ4q7iIh+Vef4ubC1c38UDsEyZynZPc=
 github.com/dimchansky/utfbom v1.0.0/go.mod h1:rO41eb7gLfo8SF1jd9F8HplJm1Fewwi4mQvIirEdv+8=
+github.com/docker/docker v1.13.1 h1:5VBhsO6ckUxB0A8CE5LlUJdXzik9cbEbBTQ/ggeml7M=
```
Comment (evan2645) [inline go.sum]: I think this was added accidentally? `go mod tidy` cleans it up

File: pkg/agent/plugin/keymanager/disk/disk.go [hunk 3]
```diff
@@ -63,6 +49,23 @@ func (d *diskPlugin) GenerateKeyPair(context.Context, *keymanager.GenerateKeyPai
...
 
+func (d *diskPlugin) StorePrivateKey(ctx context.Context, req *keymanager.StorePrivateKeyRequest) (*keymanager.StorePrivateKeyResponse, error) {
+	d.mtx.RLock()
+	if d.dir == "" {
+		d.mtx.RUnlock()
+		return nil, errors.New("path not configured")
+	}
+
+	keyPath := path.Join(d.dir, keyFileName)
+	d.mtx.RUnlock()
```
[the remark this answers is not in the document]
Comment (azdagron) [reply pkg/agent/plugin/keymanager/disk/disk.go]: We should take the write lock in this case, instead of the read lock.

[the remark this answers is not in the document]
Comment (APTy) [reply pkg/agent/plugin/keymanager/disk/disk.go]: yeah probably want an in-memory write lock to be safe, plus an atomic file write (from diskutil)

File: pkg/agent/svid/rotator.go (hunk 1 above)
Comment (APTy) [reply pkg/agent/svid/rotator.go]: +1 agree with this

**Comment by evan2645** [comment]
Gonna close and re-open this hoping that GH will poke travis again...
