### PR TITLE
Validate KeyManager directory on agent startup

### LINKED ISSUE #5488: Spire-Agent is failing to rotate its SVID due to Missing KeyManager directory
We noticed that due to missing KeyManager directory on the host, spire-agent is failing to rotate its keys. 

To avoid this we could add a check in the disk keymanager 'writeEntries' method: https://github.com/spiffe/spire/blob/main/pkg/agent/plugin/keymanager/disk/disk.go#L108

### PR DESCRIPTION
**Pull request by akos011221**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
disk KeyManager plugin 

**Description of change**
Validation is added in the `disk` KeyManager plugin `Configure()` method that validates the configured directory (creates it if it doesn't exist), also verifying the permissions in the directory.

**Which issue this PR fixes**
fixes #5488

### CODE REVIEW

File: pkg/agent/plugin/keymanager/disk/disk.go [hunk 1]
```diff
@@ -72,6 +72,10 @@ func (m *KeyManager) Configure(_ context.Context, req *configv1.ConfigureRequest
 		return nil, status.Error(codes.InvalidArgument, "directory must be configured")
 	}
 
+	if err := m.verifyDirectory(config.Directory); err != nil {
+		return nil, status.Errorf(codes.FailedPrecondition, "directory validation failed")
```
Comment (MarcosDY) [inline pkg/agent/plugin/keymanager/disk/disk.go]: this is going to be hard to debug since error is missed here, 
can you update to:
```
		return nil, status.Errorf(codes.FailedPrecondition, "directory validation failed: %v", err)
```

File: pkg/agent/plugin/keymanager/disk/disk_test.go [hunk 2]
```diff
@@ -32,6 +32,23 @@ func TestConfigure(t *testing.T) {
...
 		spiretest.RequireGRPCStatus(t, err, codes.InvalidArgument, "directory must be configured")
 	})
+	t.Run("directory created if missing", func(t *testing.T) {
+		dir := filepath.Join(spiretest.TempDir(t), "no-such-dir")
+
+		_, err := os.Stat(dir)
+		require.True(t, os.IsNotExist(err))
+
+		_, err = loadPlugin(t, "directory = %q", dir)
+		require.NoError(t, err)
```
Comment (MarcosDY) [inline pkg/agent/plugin/keymanager/disk/disk_test.go:43]: can you verify than folder was created?

Comment (akos011221) [reply pkg/agent/plugin/keymanager/disk/disk_test.go:43]: Yes, added a check.

File: pkg/agent/plugin/keymanager/disk/disk.go (hunk 1 above)
Comment (akos011221) [reply pkg/agent/plugin/keymanager/disk/disk.go]: Yes, done.
