### PR TITLE
Remove configuration constraint for k8s_psat

### LINKED ISSUE #5211: k8s_psat node attestor: allow empty list of clusters
Now that the plugin configuration can be reloaded at runtime to add and remove new clusters it's possible to end up in the situation where you have a mostly valid configuration file (at least from the administrator point of view) with no clusters defined. 

This configuration is rejected by spire-server (see https://github.com/spiffe/spire/blob/04a0bcd1ad0f600241f3c9749a264fe689139a8a/pkg/server/plugin/nodeattestor/k8spsat/psat.go#L228). This might lead to situations where spire-server is unable to start up (e.g. if it crashes and has to restart), even though it might have still been able to serve other agents with other node attestors.

Would it be possible to remove that check? I can work around it by adding some dummy value in there, but that seems a bit icky to me.

* **Version**: 1.10.0
* **Platform**: any
* **Subsystem**: k8s_psat server nodeattestor

### PR DESCRIPTION
**Pull request by edwbuck**
Closes #5211

We already scan the map of clusters at runtime, sending an error when the cluster is not found in the hclConfig.Clusters map.  So, this just removes the need for at least one cluster to be configured.

When zero clusters are configured, all requests will fail.

### CODE REVIEW

File: pkg/server/plugin/nodeattestor/k8spsat/psat.go [hunk 1]
```diff
@@ -225,10 +226,6 @@ func (p *AttestorPlugin) Configure(_ context.Context, req *configv1.ConfigureReq
 		return nil, status.Error(codes.InvalidArgument, "core configuration missing trust domain")
 	}
 
-	if len(hclConfig.Clusters) == 0 {
```
Comment (azdagron) [inline pkg/server/plugin/nodeattestor/k8spsat/psat.go:228]: Not having any clusters defined would be a misconfiguration for (most?) users that aren't dynamically adjusting the list. To aid debuggability, can you change this to emit a warning log instead? The log warning should be emitted down below, just before the call to p.setConfig, so that we only emit the warning when the configuration is actually going to change.

File: doc/plugin_server_nodeattestor_k8s_psat.md [hunk 2]
```diff
@@ -20,6 +20,7 @@ The main configuration accepts the following values:
 | Configuration | Description                                                                       | Default |
 |---------------|-----------------------------------------------------------------------------------|---------|
 | `clusters`    | A map of clusters, keyed by an arbitrary ID, that are authorized for attestation. |         |
+|               | May be empty, when no clusters are authorized for attestation.                    |         |
```
Comment (azdagron) [inline doc/plugin_server_nodeattestor_k8s_psat.md:23]: This renders as a separate row in the markdown and looks a little funny. I feel like we should just add this to the end of the sentence in the description above.

File: pkg/server/plugin/nodeattestor/k8spsat/psat.go (hunk 1 above)
Comment (edwbuck) [reply pkg/server/plugin/nodeattestor/k8spsat/psat.go:228]: A WARNING log message is appropriate.  Expect an update today.

File: doc/plugin_server_nodeattestor_k8s_psat.md (hunk 2 above)
Comment (edwbuck) [reply doc/plugin_server_nodeattestor_k8s_psat.md:23]: Altered to be a warning note in the next push.

File: pkg/server/plugin/nodeattestor/k8spsat/psat.go [hunk 3]
```diff
@@ -226,6 +226,10 @@ func (p *AttestorPlugin) Configure(_ context.Context, req *configv1.ConfigureReq
 		return nil, status.Error(codes.InvalidArgument, "core configuration missing trust domain")
 	}
 
+	if len(hclConfig.Clusters) < 1 {
```
Comment (azdagron) [inline pkg/server/plugin/nodeattestor/k8spsat/psat.go:229]: This warning should ideally be moved to down to line 274 just before the call to p.setConfig. The configure call can still fail at this point (i.e., line 240) leaving the configuration unchanged. Issuing the warning before the config is actually changed could be misleading.

**Review by azdagron — APPROVED** [review]
Thanks, @edwbuck!
