### PR TITLE
Remove go health dependency

### LINKED ISSUE #3506: go-health dependency is failing to load dependency
go-health that is using in the heath check process is failing to load a deleted dependency.
It is an already [know issue ](https://github.com/InVisionApp/go-health/releases/tag/v2.1.3)
```
> [builder 4/7] RUN cd /spire && go mod download:
#13 86.77 go: github.com/InVisionApp/go-health/v2@v2.1.2 requires
#13 86.77       github.com/zaffka/mongodb-boltdb-mock@v0.0.0-20180816124423-49954d88fa3e: invalid version: git ls-remote -q origin in /go/pkg/mod/cache/vcs/6a5c38c13a58195bdda5700746945af5b4899cebeb3da0a5bc22c5d45317c7b3: exit status 128:
#13 86.77       fatal: could not read Username for 'https://github.com/': terminal prompts disabled
#13 86.77 Confirm the import path was entered correctly.
#13 86.77 If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
------
```

### PR DESCRIPTION
**Pull request by MarcosDY**
Remove go-helper dependency in favor of in house code.

**Which issue this PR fixes**
fixes #3506

### CODE REVIEW

File: pkg/common/health/cache.go [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+
+	if _, ok := c.allowedChecks[name]; ok {
+		return fmt.Errorf("check %q has already been added", name)
+	}
+
+	c.allowedChecks[name] = checkable
+	return nil
+}
+
+func (c *Cache) GetStatuses() map[string]CheckState {
```
Comment (azdagron) [inline pkg/common/health/cache.go:71]: It is dangerous to return a reference type that is protected by a lock since the caller can then mutate the reference object without going through the lock. Although unlikely this will be a problem if the map is mutated while the checker is reading the map.

File: pkg/common/health/cache.go [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+	c.mutex.Lock()
+	defer c.mutex.Unlock()
+
+	return c.currentStatus
+}
+
+func (c *Cache) Start(ctx context.Context) error {
+	if len(c.allowedChecks) < 1 {
```
Comment (azdagron) [inline pkg/common/health/cache.go:79]: allowedChecks is referenced here without this function taking the lock.

File: pkg/common/health/cache.go [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+		log:           log,
+		clk:           clock,
+	}
+}
+
+type Cache struct {
+	allowedChecks map[string]Checkable
+
+	currentStatus map[string]CheckState
+	mutex         sync.Mutex
```
Comment (azdagron) [inline pkg/common/health/cache.go:46]: Can we benefit from a RW mutex here?

**Review by azdagron — COMMENTED** [review]
I didn't quite finish my review. I'll do that tomorrow morning, but here are some comments so far.

File: pkg/common/health/cache.go [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+func NewCache(log logrus.FieldLogger, clock clock.Clock) *Cache {
+	return &Cache{
+		allowedChecks: make(map[string]Checkable),
+		currentStatus: make(map[string]CheckState),
+		log:           log,
+		clk:           clock,
+	}
+}
+
+type Cache struct {
```
[the remark this answers is not in the document]
Comment (MarcosDY) [reply pkg/common/health/cache.go:42]: I was for testing purposes, I don't like adding unit tests to unexported functions, I'll make them private now

File: pkg/common/health/cache_test.go [hunk 5]
```diff
@@ -0,0 +1,320 @@
...
+					"error": "subsystem is not live or ready",
+				},
+			},
+		}
+
+		spiretest.AssertLogs(t, hook.AllEntries(), expectLogs)
+		require.Equal(t, expectStatus, cache.GetStatuses())
+	})
+
+	// Health start to fail
```
Comment (guilhermocc) [inline pkg/common/health/cache_test.go:249]:
```suggestion
	// Health start to recover
```

File: pkg/common/health/health_test.go [hunk 6]
```diff
@@ -20,3 +27,115 @@ func TestServerEnabled(t *testing.T) {
...
+			Ready:        true,
+			ReadyDetails: healthDetails{},
+			LiveDetails:  healthDetails{},
+		},
+	}
+	err = servableChecker.AddCheck("bar", barChecker)
+	require.NoError(t, err)
+
+	// Get chage to set a chan in order to wait until sync is done
+	finalCheker, ok := servableChecker.(*checker)
```
Comment (guilhermocc) [inline pkg/common/health/health_test.go:65]:
```suggestion
	finalChecker, ok := servableChecker.(*checker)
```

File: pkg/common/health/health_test.go [hunk 7]
```diff
@@ -20,3 +27,115 @@ func TestServerEnabled(t *testing.T) {
...
+			Live:         true,
+			Ready:        true,
+			ReadyDetails: healthDetails{},
+			LiveDetails:  healthDetails{},
+		},
+	}
+	err = servableChecker.AddCheck("bar", barChecker)
+	require.NoError(t, err)
+
+	// Get chage to set a chan in order to wait until sync is done
```
Comment (guilhermocc) [inline pkg/common/health/health_test.go:64]:
```suggestion
	// Get change to set a chan in order to wait until sync is done
```

File: pkg/common/health/cache.go [hunk 8]
```diff
@@ -0,0 +1,192 @@
...
+}
+
+func (c *cache) embellishState(name string, state *checkState) {
+	// get the previous state
+	c.mtx.RLock()
+	prevState := c.currentStatus[name]
+	c.mtx.RUnlock()
+
+	switch {
+	case state.err != nil && prevState.err == nil:
```
Comment (azdagron) [inline pkg/common/health/cache.go:150]: nit: i wonder if this might be more readable if we enumerate each case, the dual condition on the first case makes it little more work to determine the state at each case that we might be able to avoid:
```suggestion
	case state.err == nil && prevState.err == nil:
	case state.err != nil && prevState.err == nil:
	case state.err == nil && prevState.err != nil:
	case state.err != nil && prevState.err != nil:
```

File: pkg/common/health/cache.go [hunk 9]
```diff
@@ -0,0 +1,192 @@
...
+		// State start to fail, add log and set failures tracking
+		c.log.WithFields(logrus.Fields{
+			"check":   name,
+			"details": state.details,
+			"error":   state.err.Error(),
```
Comment (azdagron) [inline pkg/common/health/cache.go:155]: for better or worse, we usually put these field names in the common/telemetry package

File: pkg/common/health/health_test.go [hunk 10]
```diff
@@ -20,3 +27,114 @@ func TestServerEnabled(t *testing.T) {
...
+	t.Run("live fails", func(t *testing.T) {
+		resp, err := http.Get("http://localhost:12345/live")
+		require.NoError(t, err)
+		defer resp.Body.Close()
+
+		require.Equal(t, http.StatusInternalServerError, resp.StatusCode)
+
+		actual, err := io.ReadAll(resp.Body)
+		require.NoError(t, err)
+		require.Equal(t, "{\"bar\":{},\"foo\":{\"err\":\"live fails\"}}\n", string(actual))
```
Comment (azdagron) [inline pkg/common/health/health_test.go:126]: require.JSONEq is more robust for this kind of assertion

File: pkg/common/health/health_test.go [hunk 11]
```diff
@@ -20,3 +27,114 @@ func TestServerEnabled(t *testing.T) {
...
+	t.Run("ready fails", func(t *testing.T) {
+		resp, err := http.Get("http://localhost:12345/ready")
+		require.NoError(t, err)
+		defer resp.Body.Close()
+
+		require.Equal(t, http.StatusInternalServerError, resp.StatusCode)
+
+		actual, err := io.ReadAll(resp.Body)
+		require.NoError(t, err)
+		require.Equal(t, "{\"bar\":{\"err\":\"ready fails\"},\"foo\":{}}\n", string(actual))
```
Comment (azdagron) [inline pkg/common/health/health_test.go:138]: require.JSONEq is more robust for this kind of assertion

**Review by azdagron — APPROVED** [review]
Thanks, @MarcosDY ! Very happy to be losing this dependency.
