### PR TITLE
agent/client: Fail hard on dial errors

### LINKED ISSUE #1339: spire agent log message not clear when spire-server service name is missconfigured
* **Version**: a211e075c1f44026efdeb89e9a9081e1898d5214
* **Platform**: kubernetes cluster
* **Subsystem**: agent

spire-agents restarting with`level=error msg="agent crashed" error="opening stream for attestation: rpc error: code = Canceled desc = context canceled"`

This was due to having miss-configured the spire-server service name in my spire-agent config.

Log message is not clear with regards to issue. Maybe this could be improved.

### PR DESCRIPTION
**Pull request by APTy**
This makes dns-related errors more obvious to the application.

For example, if a bad server name is provided in the agent config,
the agent will crash at startup, rather than hang indefinitely.

Fixes #1339

## Before this change

On master with `server_address = "foobar"` in `agent.conf`, this is the behavior for agent startup and when a dns entry goes bad after agent is already running.

### Agent startup
```
WARN[0000] Current umask 0022 is too permissive; setting umask 0027.
INFO[0000] Starting agent with data directory: "./.data"
...
WARN[0000] Private key recovered, but SVID is expired. Generating new keypair.  subsystem_name=attestor
```
(hangs indefinitely)

### DNS change after agent is running
```
INFO[0000] Starting agent with data directory: "./.data"
...
DEBU[0001] Bundle updated                                subsystem_name=cache_manager trust_domain_id="spiffe://example.org"
DEBU[0001] Entry created                                 entry=5c487059-a64c-4fea-a358-7e9ca9f86928 selectors_added=1 spiffe_id="spiffe://example.org/foo/bar" subsystem_name=cache_manager
INFO[0001] Renewing X509-SVID                            spiffe_id="spiffe://example.org/foo/bar" subsystem_name=manager
DEBU[0001] Entry updated                                 entry=5c487059-a64c-4fea-a358-7e9ca9f86928 spiffe_id="spiffe://example.org/foo/bar" subsystem_name=cache_manager svid_updated=true
DEBU[0001] Starting checker                              name=agent subsystem_name=health
INFO[0001] Starting workload API                         subsystem_name=endpoints

*** Changed DNS record here ***

ERRO[0201] Failure fetching X509 SVID. unable to get a stream  error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>" subsystem_name=manager
ERRO[0201] synchronize failed                            error="unable to get a stream" subsystem_name=manager
```

### Agent startup

```
WARN[0000] Current umask 0022 is too permissive; setting umask 0027.
INFO[0000] Starting agent with data directory: "./.data"
...
WARN[0000] Private key recovered, but SVID is expired. Generating new keypair.  subsystem_name=attestor
ERRO[0002] agent crashed                                 error="create attestation client: failed to dial dns:///foobar:8081: context deadline exceeded"
```

### DNS change after agent running
```
WARN[0000] Current umask 0022 is too permissive; setting umask 0027.
INFO[0000] Starting agent with data directory: "./.data"
...
WARN[0000] Private key recovered, but SVID is expired. Generating new keypair.  subsystem_name=attestor
DEBU[0002] Entry created                                 entry=924dc93b-210a-4b58-b9d3-c5298ce8cd8a selectors_added=1 spiffe_id="spiffe://example.org/foo/bar" subsystem_name=cache_manager
INFO[0002] Renewing X509-SVID                            spiffe_id="spiffe://example.org/foo/bar" subsystem_name=manager
DEBU[0002] Entry updated                                 entry=924dc93b-210a-4b58-b9d3-c5298ce8cd8a spiffe_id="spiffe://example.org/foo/bar" subsystem_name=cache_manager svid_updated=true
DEBU[0002] Starting checker                              name=agent subsystem_name=health
INFO[0002] Starting workload API                         subsystem_name=endpoints

*** Changed DNS record here ***

ERRO[0192] Failure fetching X509 SVID. unable to get a stream  error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>" subsystem_name=manager
ERRO[0192] synchronize failed                            error="unable to get a stream" subsystem_name=manager
ERRO[0204] synchronize failed                            error="failed to dial dns:///foobar:8081: context deadline exceeded" subsystem_name=manager
```

### CODE REVIEW

File: pkg/agent/client/dial.go [hunk 1]
```diff
@@ -65,9 +71,17 @@ func DialServer(ctx context.Context, config DialServerConfig) (*grpc.ClientConn,
...
 	}
 
-	return grpc.DialContext(ctx, config.Address,
+	ctx, cancel := context.WithTimeout(ctx, _defaultDialTimeout)
+	defer cancel()
+
+	client, err := grpc.DialContext(ctx, config.Address,
 		grpc.WithBalancerName(roundrobin.Name), //nolint:staticcheck
 		grpc.FailOnNonTempDialError(true),
+		grpc.WithBlock(),
```
Comment (APTy) [inline pkg/agent/client/dial.go:80]: `WithBlock()` is required here: `FailOnNonTempDialError only affects the initial dial, and does not do anything useful unless you are also using WithBlock().` (from https://godoc.org/google.golang.org/grpc#FailOnNonTempDialError)

File: pkg/agent/client/dial.go [hunk 2]
```diff
@@ -65,9 +74,20 @@ func DialServer(ctx context.Context, config DialServerConfig) (*grpc.ClientConn,
...
+	}
+	client, err := config.dialContext(ctx, config.Address,
 		grpc.WithBalancerName(roundrobin.Name), //nolint:staticcheck
 		grpc.FailOnNonTempDialError(true),
+		grpc.WithBlock(),
 		grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)),
 	)
+	if err != nil {
+		return nil, fmt.Errorf("failed to dial %v: %v", config.Address, err)
+	}
```
Comment (azdagron) [inline pkg/agent/client/dial.go:91]: I wonder if we can get better error messaging by checking for specific error classes? "context deadline exceeded" makes sense to developers used to dealing with golang context's but not to the average operator.

```suggestion
	switch {
	case err == nil:
	case errors.Is(err, context.Canceled):
		return nil, fmt.Errorf("failed to dial %s: canceled", config.Address)
	case errors.Is(err, context.DeadlineExceeded):
		return nil, fmt.Errorf("failed to dial %s: timed out", config.Address)
	default:
		return nil, fmt.Errorf("failed to dial %s: %v", config.Address, err)
	}
```
