### PR TITLE
test: Adds require.Eventually to help with flaky endpoint test

### LINKED ISSUE #6314: Flaky test suite TestListenAndServe
This fails from time to time in CI:

```
--- FAIL: TestListenAndServe (0.26s)
    --- FAIL: TestListenAndServe/Agent (0.05s)
        --- FAIL: TestListenAndServe/Agent/Local (0.00s)
            --- FAIL: TestListenAndServe/Agent/Local/AttestAgent (0.00s)
                endpoints_test.go:1117: 
                    	Error Trace:	/home/runner/work/spire/spire/pkg/server/endpoints/endpoints_test.go:1117
                    	            				/home/runner/work/spire/spire/pkg/server/endpoints/endpoints_test.go:1036
                    	Error:      	Expected nil, but got: &status.Error{s:(*status.Status)(0xc00071ea98)}
                    	Test:       	TestListenAndServe/Agent/Local/AttestAgent
                    	Messages:   	should have succeeded getting the stream
            --- FAIL: TestListenAndServe/Agent/Local/BanAgent (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Agent/Local/CountAgents (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Agent/Local/CreateJoinToken (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Agent/Local/DeleteAgent (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Agent/Local/GetAgent (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Agent/Local/ListAgents (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Agent/Local/PostStatus (0.00s)
                endpoints_test.go:1056: should not have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Agent/Local/RenewAgent (0.00s)
                endpoints_test.go:1056: should not have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            endpoints_test.go:1064: "AttestAgent" had an expected result but is not part of the *agentv1.agentClient interface
    --- FAIL: TestListenAndServe/Debug (0.00s)
        --- FAIL: TestListenAndServe/Debug/Local (0.00s)
            --- FAIL: TestListenAndServe/Debug/Local/GetInfo (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
    --- FAIL: TestListenAndServe/Health (0.00s)
        --- FAIL: TestListenAndServe/Health/Local (0.00s)
            --- FAIL: TestListenAndServe/Health/Local/Check (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Health/Local/List (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Health/Local/Watch (0.00s)
                endpoints_test.go:1117: 
                    	Error Trace:	/home/runner/work/spire/spire/pkg/server/endpoints/endpoints_test.go:1117
                    	            				/home/runner/work/spire/spire/pkg/server/endpoints/endpoints_test.go:1036
                    	Error:      	Expected nil, but got: &status.Error{s:(*status.Status)(0xc000fb6360)}
                    	Test:       	TestListenAndServe/Health/Local/Watch
                    	Messages:   	should have succeeded getting the stream
            endpoints_test.go:1064: "Watch" had an expected result but is not part of the *grpc_health_v1.healthClient interface
    --- FAIL: TestListenAndServe/Logger (0.00s)
        --- FAIL: TestListenAndServe/Logger/Local (0.00s)
            --- FAIL: TestListenAndServe/Logger/Local/GetLogger (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Logger/Local/ResetLogLevel (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Logger/Local/SetLogLevel (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
    --- FAIL: TestListenAndServe/Bundle (0.05s)
        --- FAIL: TestListenAndServe/Bundle/Local (0.00s)
            --- FAIL: TestListenAndServe/Bundle/Local/AppendBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/BatchCreateFederatedBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/BatchDeleteFederatedBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/BatchSetFederatedBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/BatchUpdateFederatedBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/CountBundles (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/GetBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/GetFederatedBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/ListFederatedBundles (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Bundle/Local/PublishJWTAuthority (0.00s)
                endpoints_test.go:1056: should not have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
    --- FAIL: TestListenAndServe/Entry (0.03s)
        --- FAIL: TestListenAndServe/Entry/Local (0.00s)
            --- FAIL: TestListenAndServe/Entry/Local/BatchCreateEntry (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Entry/Local/BatchDeleteEntry (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Entry/Local/BatchUpdateEntry (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Entry/Local/CountEntries (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Entry/Local/GetAuthorizedEntries (0.00s)
                endpoints_test.go:1056: should not have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Entry/Local/GetEntry (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Entry/Local/ListEntries (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/Entry/Local/SyncAuthorizedEntries (0.00s)
                endpoints_test.go:1117: 
                    	Error Trace:	/home/runner/work/spire/spire/pkg/server/endpoints/endpoints_test.go:1117
                    	            				/home/runner/work/spire/spire/pkg/server/endpoints/endpoints_test.go:1036
                    	Error:      	Expected nil, but got: &status.Error{s:(*status.Status)(0xc000559eb0)}
                    	Test:       	TestListenAndServe/Entry/Local/SyncAuthorizedEntries
                    	Messages:   	should have succeeded getting the stream
            endpoints_test.go:1064: "SyncAuthorizedEntries" had an expected result but is not part of the *entryv1.entryClient interface
    --- FAIL: TestListenAndServe/SVID (0.02s)
        --- FAIL: TestListenAndServe/SVID/Local (0.00s)
            --- FAIL: TestListenAndServe/SVID/Local/BatchNewX509SVID (0.00s)
                endpoints_test.go:1056: should not have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/SVID/Local/MintJWTSVID (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/SVID/Local/MintX509SVID (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/SVID/Local/NewDownstreamX509CA (0.00s)
                endpoints_test.go:1056: should not have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/SVID/Local/NewJWTSVID (0.00s)
                endpoints_test.go:1056: should not have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
    --- FAIL: TestListenAndServe/TrustDomain (0.03s)
        --- FAIL: TestListenAndServe/TrustDomain/Local (0.00s)
            --- FAIL: TestListenAndServe/TrustDomain/Local/BatchCreateFederationRelationship (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/TrustDomain/Local/BatchDeleteFederationRelationship (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/TrustDomain/Local/BatchUpdateFederationRelationship (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/TrustDomain/Local/GetFederationRelationship (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/TrustDomain/Local/ListFederationRelationships (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/TrustDomain/Local/RefreshBundle (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
    --- FAIL: TestListenAndServe/LocalAuthority (0.05s)
        --- FAIL: TestListenAndServe/LocalAuthority/Local (0.00s)
            --- FAIL: TestListenAndServe/LocalAuthority/Local/ActivateJWTAuthority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/ActivateX509Authority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/GetJWTAuthorityState (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/GetX509AuthorityState (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/PrepareJWTAuthority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/PrepareX509Authority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/RevokeJWTAuthority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/RevokeX509Authority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/RevokeX509UpstreamAuthority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/TaintJWTAuthority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/TaintX509Authority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
            --- FAIL: TestListenAndServe/LocalAuthority/Local/TaintX509UpstreamAuthority (0.00s)
                endpoints_test.go:1052: should have been authorized; code=Unavailable msg=connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-test-579368453/sockets: connect: no such file or directory"
FAIL
FAIL	github.com/spiffe/spire/pkg/server/endpoints	2.800s
```

### PR DESCRIPTION
**Pull request by jsnctl**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

Test suite, specifically `pkg/server/endpoints`

**Description of change**

* Previously we saw CI failures when /tmp/spire-test-*/sockets wasn't ready after goroutine kickoff for the test case
* This change adds an Eventually case to ensure the socket is available in the filesystem within a set period before proceeding

**Which issue this PR fixes**

fixes #6314 

---

It was tricky to properly recreate this: even with `stress` and resource contention locally my CPU seemed to always populate the tmp socket with no trouble. I was able to sort of approximate by adding a `time.Sleep()` < 1s to the goroutine used to kick off `ListenAndServe` to delay the socket being available.

e.g.

```diff
// Start listening
	errCh := make(chan error)
	go func() {
+		time.Sleep(500 * time.Millisecond) # diagnostic 
		errCh <- endpoints.ListenAndServe(ctx)
	}()
```

If we're happy that 1s is plenty of an upper timeout for the CI to handle the socket creation per case, then I think this should mitigate this flakiness re-occuring

### CODE REVIEW

File: pkg/server/endpoints/endpoints_test.go [hunk 1]
```diff
@@ -263,6 +264,14 @@ func TestListenAndServe(t *testing.T) {
 		return conn
 	}
 
+	// Await /tmp/spire-test-*/sockets to become available (within 1s)
+	// Avoids flaky tests in CI, where we occasionally see failures
+	// due to the socket not being ready when first used by the test
+	require.Eventually(t, func() bool {
+		_, err := os.Stat(endpoints.LocalAddr.String())
+		return err == nil
+	}, time.Second, 10*time.Millisecond, "socket %q not available", endpoints.LocalAddr.String())
```
Comment (sorindumitru) [inline pkg/server/endpoints/endpoints_test.go]: I think this makes sense since gRPC doesn't seem to provide a better way of checking if the server is up. 
Could we increase the timeout to be a big higher. Maybe 10 seconds? CI might be slower and in most cases it should finish quickly anyway.

Comment (jsnctl) [reply pkg/server/endpoints/endpoints_test.go]: Thanks @sorindumitru, I've amended to 10s https://github.com/spiffe/spire/pull/6417/commits/b3dcec3760a3d60f543225085922a0a48a9dfa77

**Comment by sorindumitru** [comment]
@jsnctl Looks like the last commit is missing DCO, would you mind adding that to it?
