### PR TITLE
Log errors in failed user/group name lookup in unix workload attestor

### LINKED ISSUE #2040: unix attestation logic should not drop errors on failed group look up
ref. https://github.com/spiffe/spire/blob/a90c73d26fd37de47dc20c461f38eed92df5a3c1/pkg/agent/plugin/workloadattestor/unix/unix.go#L265

```
func (p *Plugin) getGroupName(gid string) (string, bool) {
	g, err := p.hooks.lookupGroupByID(gid)
	if err != nil {
		return "", false
	}
	return g.Name, true
}
```
If there is an error looking up groups, we simply drop the error.

The caller of this function also does not even log the "false" return as a problem:
```
	if group, ok := p.getGroupName(gid); ok {
		selectors = append(selectors, makeSelector("group", group))
	}
```

Improvements:
- We should log the actual error with details.
- Should unix attestation fail if group lookup fails?

### PR DESCRIPTION
**Pull request by rturner3**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
`unix` Workload Attestor plugin

**Description of change**
Adding logging in cases where looking up a Unix user name by `uid` or a Unix group name by `gid` fails. Currently, the `unix` attestor swallows these errors without logging or returning them. This makes it difficult to understand workload attestation failures that might be caused by one of the `unix:user` or `unix:group` selectors not being properly identified.

**Which issue this PR fixes**
fixes #2040

### CODE REVIEW

File: pkg/agent/plugin/workloadattestor/unix/unix.go [hunk 1]
```diff
@@ -241,6 +247,7 @@ func (p *Plugin) getUID(proc processInfo) (string, error) {
 func (p *Plugin) getUserName(uid string) (string, bool) {
 	u, err := p.hooks.lookupUserByID(uid)
 	if err != nil {
+		p.log.Warn("failed to lookup user name by uid", "uid", uid, "error", err)
```
Comment (azdagron) [inline pkg/agent/plugin/workloadattestor/unix/unix.go:250]: nit: log messages should start with uppercase

File: pkg/agent/plugin/workloadattestor/unix/unix.go [hunk 2]
```diff
@@ -265,6 +272,7 @@ func (p *Plugin) getGID(proc processInfo) (string, error) {
 func (p *Plugin) getGroupName(gid string) (string, bool) {
 	g, err := p.hooks.lookupGroupByID(gid)
 	if err != nil {
+		p.log.Warn("failed to lookup group name by gid", "gid", gid, "error", err)
```
Comment (azdagron) [inline pkg/agent/plugin/workloadattestor/unix/unix.go:275]: nit: log messages should start with uppercase

**Review by azdagron — COMMENTED** [review]
Thanks for this @rturner3. Other than the nitpicks on the log casing, I was wondering how you felt about throwing together a few test cases to test the logging? Should hopefully be a quick addition to the PR.

File: pkg/agent/plugin/workloadattestor/unix/unix.go (hunk 1 above)
Comment (rturner3) [reply pkg/agent/plugin/workloadattestor/unix/unix.go]: Good catch!

File: pkg/agent/plugin/workloadattestor/unix/unix.go (hunk 2 above)
Comment (rturner3) [reply pkg/agent/plugin/workloadattestor/unix/unix.go]: > Thanks for this @rturner3. Other than the nitpicks on the log casing, I was wondering how you felt about throwing together a few test cases to test the logging? Should hopefully be a quick addition to the PR.

Sure, added some test coverage.

**Review by azdagron — APPROVED** [review]
\o/
