### PR TITLE
Fix phony bundle updates

### LINKED ISSUE #3101: Fetch bundles methods are generating phony updates
Using the `WatchX509Bundles` method from `go-spiffe` library I’m seeing that the updates arrive based on the `SVID_TTL` and not on the `CA_TTL` as I’d expect.

Looking into the SPIRE workload handler, the `FetchX509Bundles` method is using `SubscribeToCacheChanges`, thus it's generating phony updates.

* **Version**: Any
* **Platform**: Any
* **Subsystem**: Agent

### PR DESCRIPTION
**Pull request by maxlambrecht**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**
Change the behavior of the Fetch bundle methods in the workload handler so they only send the updates when they are new bundles, preventing spurious updates.

**Which issue this PR fixes**
`fixes #3101`

Signed-off-by: Max Lambrecht <max.lambrecht@hpe.com>

### CODE REVIEW

File: pkg/agent/endpoints/workload/handler.go [hunk 1]
```diff
@@ -375,24 +382,28 @@ func composeX509SVIDResponse(update *cache.WorkloadUpdate) (*workload.X509SVIDRe
...
 	}
 
 	resp, err := composeJWTBundlesResponse(update)
 	if err != nil {
 		log.WithError(err).Error("Could not serialize JWT bundle response")
-		return status.Errorf(codes.Unavailable, "could not serialize response: %v", err)
+		return nil, status.Errorf(codes.Unavailable, "could not serialize response: %v", err)
+	}
+
+	if reflect.DeepEqual(resp.GetBundles(), previousResponse.GetBundles()) {
```
Comment (azdagron) [inline pkg/agent/endpoints/workload/handler.go:397]: DeepEqual won't do the right thing here. We should use `proto.Equal` instead. We should also compare the full response instead of just the bundle fields (more robust in the face of additional fields). 
```suggestion
	if proto.Equal(resp, previousResponse) {
```

File: pkg/agent/endpoints/workload/handler.go [hunk 2]
```diff
@@ -264,24 +267,28 @@ func (h *Handler) FetchX509Bundles(_ *workload.X509BundlesRequest, stream worklo
...
 	}
 
 	resp, err := composeX509BundlesResponse(update)
 	if err != nil {
 		log.WithError(err).Error("Could not serialize X509 bundle response")
-		return status.Errorf(codes.Unavailable, "could not serialize response: %v", err)
+		return nil, status.Errorf(codes.Unavailable, "could not serialize response: %v", err)
+	}
+
+	if reflect.DeepEqual(resp.GetBundles(), previousResponse.GetBundles()) {
```
Comment (azdagron) [inline pkg/agent/endpoints/workload/handler.go:282]: DeepEqual won't do the right thing here. We should use proto.Equal instead. We should also compare the full response instead of just the bundle fields (more robust in the face of additional fields).
```suggestion
	if proto.Equal(resp, previousResponse) {
```

**Review by azdagron — COMMENTED** [review]
Thanks for this, @maxlambrecht!

Can we add a test case for this?

**Comment by maxlambrecht** [comment]
> Thanks for this, @maxlambrecht!
> 
> Can we add a test case for this?

I added a couple of tests for the FetchX509Bundles method, to cover multiple different updates and spurious updates. Let me know if they are ok and I'll add similar tests for the FetchJWTBundles.

File: pkg/agent/endpoints/workload/handler_test.go [hunk 3]
```diff
@@ -321,6 +321,122 @@ func TestFetchX509Bundles(t *testing.T) {
...
+		CA:                            ca,
+		Updates:                       updates,
+		AttestErr:                     nil,
+		ExpectLogs:                    nil,
+		AllowUnauthenticatedVerifiers: false,
+	}
+
+	runTest(t, params,
+		func(ctx context.Context, client workloadPB.SpiffeWorkloadAPIClient) {
+			timeoutCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
```
Comment (azdagron) [inline pkg/agent/endpoints/workload/handler_test.go:425]: Hmm, this will add 5 seconds to the unit test, correct? I wonder if there is another way we can test this deterministically without introducing this time. I have two reasons:
1. This kind of change seems small but adds up in the aggregate, increasing our already terrible CI/CD pipeline times
2. When running in CI/CD, due to the often resource constrained running environment, waiting for small time values like this doesn't always mean that the code we're waiting on had the chance to do everything. For example, in this case, it could be that another response was going to be sent down the stream, but the code was executing slowly enough that it would have taken longer than five seconds to do so. In which case we'd have a false positive indication of success.

One way we might be able to test this deterministically is by creating a test hook in the stream response loop so we can determine that we've received an update from the cache, we've sent the response (or not if there was a change) and are waiting for the next update. I think we could probably implement that hook without impacting the production code by adding some code to the fakeSubscriber, which gets a call to `Update` in the stream update loop.

File: pkg/agent/endpoints/workload/handler.go [hunk 4]
```diff
@@ -140,10 +141,11 @@ func (h *Handler) FetchJWTBundles(req *workload.JWTBundlesRequest, stream worklo
 	subscriber := h.c.Manager.SubscribeToCacheChanges(selectors)
 	defer subscriber.Finish()
 
+	var resp *workload.JWTBundlesResponse
```
Comment (azdagron) [inline pkg/agent/endpoints/workload/handler.go:144]: nit: can we rename this `previousResp` or something?

File: pkg/agent/endpoints/workload/handler_test.go (hunk 3 above)
Comment (maxlambrecht) [reply pkg/agent/endpoints/workload/handler_test.go:425]: I'm looking into how to test it with a hook in the stream update loop.

As an alternative, what do you think about adding a debug log?
```
if proto.Equal(resp, previousResponse) {
    log.Debug("spurious update")
    return previousResponse, nil
}
```
and add it to expectedLogs in the test.

**Review by azdagron — APPROVED** [review]
Thanks so much for this, @maxlambrecht !
