### PR TITLE
ci also runs unit tests with -race enabled, but conditionally skips flaky tests

### LINKED ISSUE #2379: Set -race flag in CI unit test runs
The project has historically had challenges with flaky tests that fail PR builds, some of which are due to race conditions due to improper synchronization in tests. In order to catch some of these types of test bugs at review time, it would be useful to run `go test` with the `-race` flag to enable race detection.

Setting `-race` comes at the cost of some added test execution time, but it prevents potential frustration for developers/maintainers that have to restart PR builds due to unrelated failing flaky tests.

### PR DESCRIPTION
**Pull request by zmt**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md
- [x] Proper tests/regressions included
- [x] Documentation updated

**Affected functionality**
Enable running the unit tests with race detector in CI/CD for PRs and releases as an additional github workflow.

Often fixing racy tests can be difficult and time-consuming. Some tests can hit negative interaction with the additional [runtime overhead](https://go.dev/doc/articles/race_detector#Runtime_Overheads) of the race detector, which can be impossible to resolve. To facilitate always running the majority of tests under the race detector:
* add SkipFlakyTestUnderRaceConditionWithIssueFiled which does the following:
  * matches arg against SPIRE issue URL regexp or fails test
  * skips tests only when SKIP_FLAKY_TESTS_UNDER_RACE_DETECTOR is in the environment
* add `ci-race-test` target in `Makefile` to set `SKIP_FLAKY_TESTS_UNDER_RACE_DETECTOR` and `-race`
* add `run_unit_tests_under_race_detector.sh` and associated workflow configuration to run `ci-race-test`

**Description of change**
Add github workflow to run tests with race detector on PRs and releases. Add utility to skip specific tests during CI/CD with the race detector and associate the skip with a github issue.

**Which issue this PR fixes**
Fixes #2379.

### CODE REVIEW

**Comment by azdagron** [comment]
I'm a little hesitant to introduce a mechanism to skip racy tests (or any tests, for that matter):

1. Skipping tests is something easily done and then forgotten. Skipped tests are worthless tests.
2. CI/CD will ideally only be running the tests with `-race`, so skipped tests equate to zero coverage.
3. With the ability to skip, the pressure to fix the racy test is severely diminished.

I think we'd get better results long term if we direct efforts at fixing the racy tests and enable `-race` everywhere.

Curious how the other maintainers feel about it though.

File: pkg/agent/plugin/nodeattestor/tpmdevid/devid_test.go [hunk 1]
```diff
@@ -473,6 +476,8 @@ func TestAidAttestationFailiures(t *testing.T) {
 }
 
 func TestAidAttestationSucceeds(t *testing.T) {
+	util.SkipFlakyTest(t)
+
```
Comment (zmt) [inline pkg/agent/plugin/nodeattestor/tpmdevid/devid_test.go:480]: Unable to repro flakiness:
```
% go test -race -count 100 -failfast -run TestAidAttestationSucceeds ./pkg/agent/plugin/nodeattestor/tpmdevid
ok  	github.com/spiffe/spire/pkg/agent/plugin/nodeattestor/tpmdevid	69.463s
```

**Comment by zmt** [comment]
* reproducing flakiness of skipped tests to file detailed issues
* adding comments referencing filed issues for all tests skipped under race detector
* adding a comment in the `SkipFlakyTest` instructing to file issue and reference in comment

**Comment by zmt** [comment]
> I'm a little hesitant to introduce a mechanism to skip racy tests (or any tests, for that matter):
> 
> 1. Skipping tests is something easily done and then forgotten. Skipped tests are worthless tests.
100% agree in principle.

> 2. CI/CD will ideally only be running the tests with `-race`, so skipped tests equate to zero coverage.
I don't agree with this assertion per se. If we run the full suite without `-race` and only conditionally skip those that are known to be problematic under `-race` in the run with that enabled, that's better than waiting until we can resolve difficult timing issues in test objects which may or may not represent actual runtime problems. The proposal in this PR is to do just that:
* run full suite: `make test`
* run almost full suite (less known issues run under `-race`): `make race-test`

> 3. With the ability to skip, the pressure to fix the racy test is severely diminished.
If we don't run the unit tests in CI/CD with `-race` at all, we don't stand a chance of catching newly introduced problems.

> 
> I think we'd get better results long term if we direct efforts at fixing the racy tests and enable `-race` everywhere.
> 
> Curious how the other maintainers feel about it though.

File: test/util/race.go [hunk 2]
```diff
@@ -7,6 +7,8 @@ import (
 	"testing"
 )
 
+const _flakyTestEnvKey = "SKIP_FLAKY_TESTS"
```
Comment (azdagron) [inline test/util/race.go:10]: stylenit:
```suggestion
const flakyTestEnvKey = "SKIP_FLAKY_TESTS"
```

File: test/util/race.go [hunk 3]
```diff
@@ -43,3 +45,10 @@ func getEnvInt(name string, fallback int) int {
 	}
 	return fallback
 }
+
+func SkipFlakyTestUnderRaceDetector(t *testing.T) {
```
Comment (azdagron) [inline test/util/race.go:49]: Can we add a comment here or maybe change the name so that it's clear new callers should not be added without careful consideration?

`SkipFlakyTestUnderRaceDetectorButYaBetterKnowWhatYouAreDoing` 😆

File: .github/workflows/scripts/run_unit_tests.sh [hunk 4]
```diff
@@ -14,3 +14,9 @@ if [ -n "${COVERALLS_TOKEN}" ]; then
     "$(go env GOPATH)"/bin/goveralls -coverprofile="${COVERPROFILE}" \
             -service=github
 fi
+
+# re-run with race detector
+echo
+echo "Re-running with race detector enabled, skipping flaky tests..."
+echo
+GOVERBOSE=1 make race-test
```
Comment (azdagron) [inline .github/workflows/scripts/run_unit_tests.sh:22]: Is there something normally lacking in the output wherein we'd want to force `-v` for CI/CD?

File: .github/workflows/scripts/run_unit_tests.sh [hunk 5]
```diff
@@ -14,3 +14,9 @@ if [ -n "${COVERALLS_TOKEN}" ]; then
     "$(go env GOPATH)"/bin/goveralls -coverprofile="${COVERPROFILE}" \
             -service=github
 fi
+
+# re-run with race detector
```
Comment (azdagron) [inline .github/workflows/scripts/run_unit_tests.sh:18]: I think I'd prefer that these race tests are run in parallel to the normal tests by the CI/CD pipeline to hopefully not extend our pipeline run time.

**Review by azdagron — COMMENTED** [review]
Thanks for this, @zmt. We discussed this in our maintainer sync and the consensus was that this was a fine short-term fix while we get all the racy tests sorted and that we could remove it once that was accomplished.

Just a few comments :)

**Comment by rturner3** [comment]
Hey @zmt, just checking in since there hasn't been movement on this PR in the last couple weeks. Do you think you'll have time to address the comments in the next week or two? If not, I would request we close the PR for now and reopen when this is ready for review.

File: test/util/race.go (hunk 3 above)
Comment (zmt) [reply test/util/race.go:49]: I'm going to add an argument that should reference an open issue and at least match startswith or simple regex to minimally validate that it looks like an issue. Your naming suggestion reminds me of the time I had to reach for [this](https://sourcegraph.com/github.com/hashicorp/vagrant/-/blob/lib/vagrant/shared_helpers.rb?L69-74&subtree=true)...

File: .github/workflows/scripts/run_unit_tests.sh (hunk 5 above)
Comment (zmt) [reply .github/workflows/scripts/run_unit_tests.sh:18]: Should I do that as a separate script? I'm not sure the best way to do that and this was the easiest way to get started running them at all.

**Comment by zmt** [comment]
> Hey @zmt, just checking in since there hasn't been movement on this PR in the last couple weeks. Do you think you'll have time to address the comments in the next week or two? If not, I would request we close the PR for now and reopen when this is ready for review.

I didn't see this until I was already gearing up to start on it again. I thought leaving it in draft status would be OK. I've picked it back up now and hope to make quick work of it. I will be leaving it in draft mode until ready.

File: .github/workflows/scripts/run_unit_tests.sh (hunk 5 above)
Comment (zmt) [reply .github/workflows/scripts/run_unit_tests.sh]: sorted, I think

File: .github/workflows/scripts/run_unit_tests.sh (hunk 4 above)
Comment (zmt) [reply .github/workflows/scripts/run_unit_tests.sh]: Initially, just for debugging. I'm thinking of leveraging `t.Log` to report out the issues with the enhancement to require that the conditional skip must have an issue associated. Without verbose, those logs won't be visible in the CI/CD runs.

File: test/util/race.go (hunk 2 above)
Comment (zmt) [reply test/util/race.go:10]: I just noticed the commit suggestion dropdown. I already fixed it locally.

File: .github/workflows/pr_build.yaml [hunk 6]
```diff
@@ -76,6 +76,25 @@ jobs:
       - name: Run unit tests
         run: ./.github/workflows/scripts/run_unit_tests.sh
 
+  unit-test-race-detector:
+    name: Run unit tests with race detector (linux)
```
Comment (zmt) [inline .github/workflows/pr_build.yaml:80]: I've cycled on the name here a few times. I'm not happy with the current. I would love suggestions/guidance.

Comment (zmt) [inline .github/workflows/pr_build.yaml:80]: I've cycled on the name here a few times. I'm not happy with the current. I would love suggestions/guidance.

File: pkg/agent/plugin/nodeattestor/tpmdevid/devid_test.go [hunk 7]
```diff
@@ -345,7 +345,7 @@ func TestConfigureWindows(t *testing.T) {
 	}
 }
 
-func TestAidAttestationFailiures(t *testing.T) {
```
Comment (zmt) [inline pkg/agent/plugin/nodeattestor/tpmdevid/devid_test.go:348]: A little noise, but this test had been flaky when I started and the typo worked against me, so I decided to leave it a little better than I found it.

File: test/util/race.go [hunk 8]
```diff
@@ -43,3 +46,18 @@ func getEnvInt(name string, fallback int) int {
...
 }
+
+func SkipFlakyTestUnderRaceDetectorWithFiledIssue(t *testing.T, issue string) {
+	t.Helper()
+	const issuePattern = "https://github.com/spiffe/spire/issues/[[:digit:]]{4,}"
+	issueRegexp := regexp.MustCompile(issuePattern)
+	if !issueRegexp.Match([]byte(issue)) {
+		msg := "Skip only allowed with associated issue. "
+		msg += "%q does not appear to be an issue. "
+		msg += "File an issue and specify it to skip a test under race detector."
```
Comment (zmt) [inline test/util/race.go:57]: Perhaps this could use some additional wordsmithing...

File: .github/workflows/pr_build.yaml (hunk 6 above)
Comment (azdagron) [inline .github/workflows/pr_build.yaml:80]: The current incarnation definitely looks different than the rest and stands out (in a not great way :) ). How about just something simple and consistent with the other job names, like:
```suggestion
    name: unit-test (linux with race detection)
```

**Review by azdagron — COMMENTED** [review]
This is looking great. I like the enforcement that the skipped test be justified by providing an issue we track. That's a nice touch. Just one small comment on the name of the CI job and I think we're off to the races!

**Comment by zmt** [comment]
Apparently we have a flaky test even without the race detector which failed on macos :-(
