### PR TITLE
Functional tests improvements

### LINKED ISSUE #295: Registration API fails during stress tests with a high number of workloads
* **Version**: a52337e05017a8dc85ccec7b0049e18e215e7b20
* **Platform**: Ubuntu Linux
* **Subsystem**: Server

When trying to register multiple entries in a row too fast the registration API fails. You can use the stress tests to reproduce this:

1. Adjust the number of workloads (`WORKLOADS`) to a high value (e.g. 100) in `/functional/Makefile`.
2. In the root directory run `make functional`.
3. After some minutes the tests will fail with this error:

```panic: rpc error: code = Unknown desc = Error trying to create entry```

4. In `/functional/server.log` you should see one line with this error:

```time="2017-11-22T17:50:22Z" level=error msg="rpc error: code = Unknown desc = database table is locked: selectors"```

### LINKED ISSUE #305: Return distinct error when workload attestation fails and registration entries are being processed
If workload attestation fails then it's possible that the workload matches one registration entry but the agent hasn't finished processing all the entries yet.

Agent should return a distinct error while entries are being processed so that the workload knows that it should retry attestation later.

### PR DESCRIPTION
**Pull request by paul-argeniss**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [X] Documentation updated?

**Description of change**

- Added locks to SQLite datastore plugin (fixes #295).
- Agent returns distinct error when workload attestation fails and cache manager is busy (fixes #305).
The cache manager consists of several components connected through channels and detecting whether it is busy can be tricky. This solution keeps track of the number of registration entries that are being handled at all times (the "pipeline", feel free to suggest a better name). When this number is non zero it means the cache manager is busy.
- Refactored functional tests so that workloads are registered before Agent is started.

### CODE REVIEW

File: plugin/server/datastore-sqlite/sqlite.go [hunk 1]
```diff
@@ -27,12 +28,16 @@ var (
 )
 
 type sqlitePlugin struct {
-	db *gorm.DB
+	db    *gorm.DB
+	mutex *sync.Mutex
```
Comment (evan2645) [inline plugin/server/datastore-sqlite/sqlite.go]: shouldn't sqlite be handling record locking? Lots of the operations here can be performed in parallel

Comment (paul-argeniss) [reply plugin/server/datastore-sqlite/sqlite.go]: There might be a better way of handling locking using sqlite itself. I can create an issue to look into this.
