### PR TITLE
fix: handle nil NSG in VMSS NIC parseNetworkInterfaceConfig

### LINKED ISSUE #6630: Node attestor azure_imds runtime error / plugin panic
Hello,

We have tested attesting agent nodes with the [azure_imds](https://github.com/spiffe/spire/blob/main/doc/plugin_server_nodeattestor_azure_imds.md) node attestor. Our integration relied on an Application id/secret:

```hcl
NodeAttestor "azure_imds" {
    plugin_data {
        tenants = {
            "onmicrosoft.com" = {
                secret_auth = {
                    app_id = "12345678-1234-1234-1234-123456789012"
                    app_secret = "your-application-secret"
                }
                restrict_to_subscriptions = ["d5b40d61-272e-48da-beb9-05f295c42bd6"]
            }
        }
    }
}
```

We ensured reall_all permissions for this application on the target subscriptions. Starting the agent lead to this plugin panic on server side:

```console
spire-external-server-0 external-spire-server time="2026-02-05T14:30:28Z" level=error msg="Plugin panicked" cause="runtime error: invalid memory address or nil pointer dereference" external=false plugin_name=azure_imds plugin_type=NodeAttestor stack="goroutine 19407 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/spiffe/spire/pkg/common/catalog.convertPanic({0x1fe2660, 0xc00039fc00}, {0x86f340, 0x9a1aef0})\n\t/spire/pkg/common/catalog/host.go:69 +0xc5\ngithub.com/spiffe/spire/pkg/common/catalog.newBuiltInServer.streamPanicInterceptor.func1.1()\n\t/spire/pkg/common/catalog/host.go:48 +0x4d\npanic({0x86f340?, 0x9a1aef0?})\n\t/usr/local/go/src/runtime/panic.go:783 +0x132\ngithub.com/spiffe/spire/pkg/server/plugin/nodeattestor/azureimds.parseNetworkInterfaceConfig(0xc0010c43a8)\n\t/spire/pkg/server/plugin/nodeattestor/azureimds/client.go:243 +0x39\ngithub.com/spiffe/spire/pkg/server/plugin/nodeattestor/azureimds.buildVirtualMachineFromVMSSInstance(0xc001a9c480, {0xc0000baf78, 0x13})\n\t/spire/pkg/server/plugin/nodeattestor/azureimds/client.go:227 +0x339\ngithub.com/spiffe/spire/pkg/server/plugin/nodeattestor/azureimds.(*azureClient).GetVMSSInstance(0xc000d4df20, {0x1f9cee8, 0xc001538180}, {0xc0016f0450, 0x24}, {0xc0016f0420, 0x24}, {0xc0019785e0, 0x1f})\n\t/spire/pkg/server/plugin/nodeattestor/azureimds/client.go:132 +0x51c\ngithub.com/spiffe/spire/pkg/server/plugin/nodeattestor/azureimds.buildSelectors({0x1f9cee8, 0xc001538180}, 0xc000d35700, 0xc0007febd0, {0xc0016f0450, 0x24}, {0xc0016f0420, 0x24})\n\t/spire/pkg/server/plugin/nodeattestor/azureimds/imds.go:396 +0x188\ngithub.com/spiffe/spire/pkg/server/plugin/nodeattestor/azureimds.(*IMDSAttestorPlugin).Attest(0xc000ad25a0, {0x1fb5b88, 0xc00119c3f0})\n\t/spire/pkg/server/plugin/nodeattestor/azureimds/imds.go:337 +0x698\ngithub.com/spiffe/spire-plugin-sdk/proto/spire/plugin/server/nodeattestor/v1._NodeAttestor_Attest_Handler({0xf55300?, 0xc000ad25a0}, {0x1faf2f8, 0xc0009ae300})\n\t/go/pkg/mod/github.com/spiffe/spire-plugin-sdk@v1.4.4-0.20251120194148-791bbd274dc7/proto/spire/plugin/server/nodeattestor/v1/nodeattestor_grpc.pb.go:123 +0xd8\ngithub.com/spiffe/spire/pkg/common/catalog.newBuiltInServer.streamPanicInterceptor.func1({0xf55300?, 0xc000ad25a0?}, {0x1faf2f8?, 0xc0009ae300?}, 0x4ab7a87?, 0xc000a0e2e0?)\n\t/spire/pkg/common/catalog/host.go:51 +0x7d\ngoogle.golang.org/grpc.getChainStreamHandler.func1({0xf55300?, 0xc000ad25a0?}, {0x1faf2f8?, 0xc0009ae300?})\n\t/go/pkg/mod/google.golang.org/grpc@v1.78.0/server.go:1571 +0x153\ngithub.com/spiffe/spire/pkg/common/catalog.(*drainHandlers).StreamServerInterceptor(0xc0006fc780, {0xf55300, 0xc000ad25a0}, {0x1faf2f8, 0xc0009ae300}, 0xc0015a8018?, 0xc0015da080)\n\t/spire/pkg/common/catalog/builtin.go:193 +0xa2\ngoogle.golang.org/grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2({0xf55300, 0xc000ad25a0}, {0x1faf2f8, 0xc0009ae300}, 0xc0015a8018, 0xc0015da040?)\n\t/go/pkg/mod/google.golang.org/grpc@v1.78.0/server.go:1562 +0x7c\ngoogle.golang.org/grpc.(*Server).processStreamingRPC(0xc0006bd688, {0x1f9cee8, 0xc001538120}, 0xc000a5b6c0, 0xc000afa420, 0x9a69940, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.78.0/server.go:1721 +0x1151\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0006bd688, {0x1f9e158, 0xc000345040}, 0xc000a5b6c0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.78.0/server.go:1836 +0xd85\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1()\n\t/go/pkg/mod/google.golang.org/grpc@v1.78.0/server.go:1063 +0x7f\ncreated by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 114\n\t/go/pkg/mod/google.golang.org/grpc@v1.78.0/server.go:1074 +0x11d\n" subsystem_name=catalog
```

Digging into the `Microsoft.ResourceGraph` we can see that our VMs from a VM ScaleSet do not have NICs with a json key `type == "microsoft.network/networkinterfaces"` contrary to NICs of classic VMs...

IMHO the ResourceGraph requests won't return NICs from VM in VMSS: https://github.com/spiffe/spire/blob/b549ae92abe4d9d914c10ecff122ace33c2a6ddd/pkg/server/plugin/nodeattestor/azureimds/client.go#L170-L185

Are we the only ones to face such issue ? Is there a detail we are missing in the way we configure the plugin ?

### PR DESCRIPTION
**Pull request by mateenali66**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

Azure IMDS node attestation for VMSS instances.

**Description of change**

VMSS NICs don't always have a Network Security Group attached. `parseNetworkInterfaceConfig` was dereferencing `NetworkSecurityGroup.ID` unconditionally, causing a plugin panic when attesting VMSS nodes with no NSG on their NIC.

added nil checks for `Properties`, `NetworkSecurityGroup`, and `NetworkSecurityGroup.ID`. if there's no NSG the `SecurityGroup` field is left as zero-value. also guard `ipconfig.Properties` and `Subnet` against nil in the IP config loop.

added a test case for the no-NSG path in `utils_test.go`.

**Which issue this PR fixes**

fixes #6630

### CODE REVIEW

File: pkg/server/plugin/nodeattestor/azureimds/client.go [hunk 1]
```diff
@@ -239,21 +239,28 @@ func parseNetworkInterfaceConfig(interfaceConfig *armcompute.VirtualMachineScale
...
 	ni := &NetworkInterface{
 		Name: *interfaceConfig.Name,
-		SecurityGroup: SecurityGroup{
+	}
+
+	if interfaceConfig.Properties == nil {
+		return ni, nil
+	}
+
+	if interfaceConfig.Properties.NetworkSecurityGroup != nil && interfaceConfig.Properties.NetworkSecurityGroup.ID != nil {
```
Comment (sorindumitru) [inline pkg/server/plugin/nodeattestor/azureimds/client.go]: nit: could you use the same early return style for these as you did for `interfaceConfig.Properties`? I find that a bit easier to read because it leads to shorter lines.

File: pkg/server/plugin/nodeattestor/azureimds/utils_test.go [hunk 2]
```diff
@@ -529,6 +530,33 @@ func TestValidateVMSSName(t *testing.T) {
 	}
 }
 
+func TestParseNetworkInterfaceConfigNoNSG(t *testing.T) {
```
Comment (sorindumitru) [inline pkg/server/plugin/nodeattestor/azureimds/utils_test.go]: Could you move this test to a client_test.go file? That's where it would likely go, since it has nothing to do with utils.go.

File: pkg/server/plugin/nodeattestor/azureimds/client.go [hunk 3]
```diff
@@ -239,21 +239,28 @@ func parseNetworkInterfaceConfig(interfaceConfig *armcompute.VirtualMachineScale
...
+		nsgResourceGroup, nsgName, err := parseNetworkSecurityGroupID(*interfaceConfig.Properties.NetworkSecurityGroup.ID)
+		if err != nil {
+			return nil, status.Errorf(codes.Internal, "unable to parse network security group ID: %v", err)
+		}
+		ni.SecurityGroup = SecurityGroup{
```
Comment (sorindumitru) [inline pkg/server/plugin/nodeattestor/azureimds/client.go]: Looking at how this is [used](https://github.com/spiffe/spire/blob/ce16852ff4975b4524cb51106150e7eb729f9a05/pkg/server/plugin/nodeattestor/azureimds/imds.go#L430) it will lead to weird selector values if SecurityGroup if not present. We might need extra checks there (and a test for this case).

File: pkg/server/plugin/nodeattestor/azureimds/utils_test.go [hunk 4]
```diff
@@ -529,6 +530,33 @@ func TestValidateVMSSName(t *testing.T) {
...
+		},
+	}
+
+	ni, err := parseNetworkInterfaceConfig(config)
+	require.NoError(t, err)
+	require.Equal(t, nicName, ni.Name)
+	require.Equal(t, SecurityGroup{}, ni.SecurityGroup)
+	require.Len(t, ni.Subnets, 1)
+	require.Equal(t, "vnet-1", ni.Subnets[0].VNet)
+	require.Equal(t, "subnet-1", ni.Subnets[0].SubnetName)
```
Comment (sorindumitru) [inline pkg/server/plugin/nodeattestor/azureimds/utils_test.go]: It would be good to also have a test for the cases where no subnets were present.

**Comment by sorindumitru** [comment]
Also, do you have access to some Azure VMs that exhibit this issue? It would be good to verify this actually fixes it.

File: pkg/server/plugin/nodeattestor/azureimds/client.go (hunk 1 above)
Comment (mateenali66) [reply pkg/server/plugin/nodeattestor/azureimds/client.go]: refactored to sequential single-line guards for the ipconfig loop, and moved NSG parsing into a parseSecurityGroup helper that uses the same early-return pattern. each nil check is on its own line now.

File: pkg/server/plugin/nodeattestor/azureimds/utils_test.go (hunk 2 above)
Comment (mateenali66) [reply pkg/server/plugin/nodeattestor/azureimds/utils_test.go]: moved to a new client_test.go in the latest commit.

File: pkg/server/plugin/nodeattestor/azureimds/client.go (hunk 3 above)
Comment (mateenali66) [reply pkg/server/plugin/nodeattestor/azureimds/client.go]: imds.go now skips emitting the network-security-group selector when both ResourceGroup and Name are empty. added TestAttestSuccessWithVMSSNoNSG in imds_test.go that drives a VMSS with a NIC having no NSG and asserts the selector is absent from the result.

File: pkg/server/plugin/nodeattestor/azureimds/utils_test.go (hunk 4 above)
Comment (mateenali66) [reply pkg/server/plugin/nodeattestor/azureimds/utils_test.go]: added TestParseNetworkInterfaceConfigNoSubnets in client_test.go covering nil IPConfigurations, empty IPConfigurations, an ipconfig with nil Subnet, and a NIC with nil Properties.

**Comment by mateenali66** [comment]
@sorindumitru Thank you for the review, guarded both in buildVirtualMachineFromVMSSInstance: instance.ID, Name, Location, Properties, and Properties.VMID each return an error before any deref, and the NetworkProfileConfiguration nil case returns the partial VirtualMachine with no interfaces rather than panicking. also tightened the GetVMSSInstance pager loop to skip instances with nil Properties or nil VMID before the comparison. covered by TestBuildVirtualMachineFromVMSSInstanceNilFields (table-driven, six cases) and TestBuildVirtualMachineFromVMSSInstanceNoNetworkProfile.

**Comment by mateenali66** [comment]
yes. provisioned a Standard_B2ts_v2 VMSS in westeurope explicitly without an NSG on the NIC (`az vmss create --nsg ""`) and confirmed the API returns no `networkSecurityGroup` field on the wire:

```json
"networkInterfaceConfigurations": [{
  "name": "spire1f94Nic",
  "properties": {
    "ipConfigurations": [{
      "name": "spire1f94IPConfig",
      "properties": {
        "subnet": {"id": ".../subnets/spire-nsg-test-subnet"}
      }
    }],
    "primary": true
  }
}]
```

ran the patched `buildVirtualMachineFromVMSSInstance` against that exact wire payload (unmarshaled via `armcompute.VirtualMachineScaleSetVMListResult`) and it returns a `VirtualMachine` with `SecurityGroup` as the zero value and the subnet populated, no panic. the unconditional `*interfaceConfig.Properties.NetworkSecurityGroup.ID` deref in the pre-fix code is exactly what crashed in #6630. test resources torn down.

File: pkg/server/plugin/nodeattestor/azureimds/client.go [hunk 5]
```diff
@@ -205,6 +215,21 @@ func buildVirtualMachineFromVMSSInstance(instance *armcompute.VirtualMachineScal
...
+	}
+	if instance.Location == nil {
+		return nil, status.Error(codes.Internal, "vmss instance location is nil")
+	}
+	if instance.Properties == nil {
+		return nil, status.Error(codes.Internal, "vmss instance properties are nil")
+	}
+	if instance.Properties.VMID == nil {
+		return nil, status.Error(codes.Internal, "vmss instance VM ID is nil")
+	}
```
Comment (sorindumitru) [inline pkg/server/plugin/nodeattestor/azureimds/client.go:232]: I'm curious if you know the answer to this. Are some of these guaranteed to always exists or does that depend on the queries you make?
