### PR TITLE
Fix events based cache issues introduced in 1.11.0

### LINKED ISSUE #5771: Events based cache issues in SPIRE 1.11
We’ve seen some issues over the weekend with the events based cache. Instances that have restarted have taken a lot of time to populate the cache and become available:

```
{"file":"authorized_entryfetcher.go:40","func":"[github.com/spiffe/spire/pkg/server/endpoints.NewAuthorizedEntryFetcherWithEventsBasedCache](http://github.com/spiffe/spire/pkg/server/endpoints.NewAuthorizedEntryFetcherWithEventsBasedCache)","level":"info","msg":"Building event-based in-memory entry cache","subsystem_name":"endpoints","time":"2025-01-11T14:13:56Z"}
{"file":"authorized_entryfetcher.go:45","func":"[github.com/spiffe/spire/pkg/server/endpoints.NewAuthorizedEntryFetcherWithEventsBasedCache](http://github.com/spiffe/spire/pkg/server/endpoints.NewAuthorizedEntryFetcherWithEventsBasedCache)","level":"info","msg":"Completed building event-based in-memory entry cache","subsystem_name":"endpoints","time":"2025-01-11T14:41:02Z"}

```

From the metrics I can tell this it spent this time fetching registration entries. Hydrating the cache seems to now:
1) Read all entries from the datastore
2) Read all events from the datastore
3) Read all entries associated with those events

In this case we had a large number of events, maybe ~500k, which meant the server was stuck here for ~30 minutes. Looking through the past logs I can see it taking multiple seconds or minutes before.

Additionally, we mark the fetched events as processed in https://github.com/spiffe/spire/blob/a49eaad6276b4e092e25a32c5301dbafa7373cd5/pkg/server/endpoints/authorized_entryfetcher_registration_entries.go#L138, but later on we might completely bail on processing the entries associated with them due to the datastore returning an error in https://github.com/spiffe/spire/blob/a49eaad6276b4e092e25a32c5301dbafa7373cd5/pkg/server/endpoints/authorized_entryfetcher_registration_entries.go#L230. Since we then only fetch changed events from the last processed one, we might skip some entry updates.

The version of the events based cache we had in 1.10.4 doesn’t seem to have these issues. It would be worth considering reverting the latest changes to the cache since they only improve a small edge case (de-duplicating entries that might be created due to long running transactions started before the cache was hydrated; I can’t imagine there being more than a couple and usually 0 of these).  https://github.com/spiffe/spire/pull/5509 is the change that would need to be reverted.

@amoore877, @stevend-uber tagging you here since I know you were also using the events based cache.

* **Version**: >= 1.11.0 
* **Platform**: any
* **Subsystem**: server, agent

### PR DESCRIPTION
**Pull request by sorindumitru**
**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
spire-server events based cache

**Description of change**

**Which issue this PR fixes**
fixes #5771

### CODE REVIEW

File: pkg/server/endpoints/authorized_entryfetcher_attested_nodes.go [hunk 1]
```diff
@@ -215,7 +215,7 @@ func (a *attestedNodes) updateCachedNodes(ctx context.Context) error {
 	for spiffeId := range a.fetchNodes {
 		node, err := a.ds.FetchAttestedNode(ctx, spiffeId)
 		if err != nil {
-			return err
```
Comment (amartinezfayo) [inline pkg/server/endpoints/authorized_entryfetcher_attested_nodes.go:218]: Having an error here is really an expected situation?
The FetchAttestedNode function will not return an error if the record was not found (https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/sqlstore.go#L1577), so it would only return an error if there was an SQL error. Are there other error situations that we expect as normal behavior?

File: pkg/server/endpoints/authorized_entryfetcher_attested_nodes.go [hunk 2]
```diff
@@ -215,7 +215,7 @@ func (a *attestedNodes) updateCachedNodes(ctx context.Context) error {
...
+			continue
```
Comment (amartinezfayo) [inline pkg/server/endpoints/authorized_entryfetcher_attested_nodes.go:218]: Having an error here is really an expected situation?
The FetchAttestedNode function will not return an error if the record was not found (https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/sqlstore.go#L1577), so it would only return an error if there was an SQL error. Are there other error situations that we expect as normal behavior?

Comment (sorindumitru) [reply pkg/server/endpoints/authorized_entryfetcher_attested_nodes.go:218]: Yes, this would be SQL errors, either the something wrong with the request (which wouldn't be a problem) or likely transient errors which we should retry at some point.

**Comment by faisal-memon** [comment]
i can help review

File: pkg/server/endpoints/authorized_entryfetcher_registration_entries.go [hunk 3]
```diff
@@ -40,9 +40,6 @@ type registrationEntries struct {
 }
 
 func (a *registrationEntries) captureChangedEntries(ctx context.Context) error {
-	// first, reset the entries we might fetch.
-	a.fetchEntries = make(map[string]struct{})
```
Comment (faisal-memon) [inline pkg/server/endpoints/authorized_entryfetcher_registration_entries.go:44]: Where is this map being allocated now?

File: pkg/server/endpoints/authorized_entryfetcher_attested_nodes.go (hunk 2 above)
Comment (faisal-memon) [reply pkg/server/endpoints/authorized_entryfetcher_attested_nodes.go:218]: It will retry next iteration so this should be ok.

File: pkg/server/endpoints/authorized_entryfetcher_registration_entries.go (hunk 3 above)
Comment (sorindumitru) [reply pkg/server/endpoints/authorized_entryfetcher_registration_entries.go:44]: It's allocated in `buildRegistrationEntriesCache`, which is how the structure is created.

Comment (faisal-memon) [reply pkg/server/endpoints/authorized_entryfetcher_registration_entries.go:44]: Thanks.

**Review by faisal-memon — APPROVED** [review]
Looks better now.

**Review by amartinezfayo — APPROVED** [review]
Thank you @sorindumitru!
