### PR TITLE
server: Include CA Serial Number in Subject field

### LINKED ISSUE #4415: spire-agent: signature check attempts limit reached while verifying certificate chain
I find myself in the following predicament:
```
Agent crashed error="create attestation client: failed to dial dns://spire-server:443: context deadline exceeded: connection error: desc = \"transport: authentication handshake failed: x509svid: could not verify leaf certificate: x509: signature check attempts limit reached while verifying certificate chain\""
```

What’s happening there is that we run into a [crypto/x509 limit](https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/crypto/x509/verify.go;l=896). It limits how many signature checks are allowed to happen to validate a certificate, most likely to avoid DoS attacks.

The verification of a certificates starts of against the [root certs](https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/crypto/x509/verify.go;l=945) and then the intermediates. For the spire-server certificate that means we first try to build a chain with the root certs and then with an intermediates (e.g. if we have an UpstreamAuthority). `findPotentialCandidates` will try to lookup candidates by the [Issuer field of the certificate](https://cs.opensource.google/go/go/+/master:src/crypto/x509/cert_pool.go;l=133). In the case of SPIRE all roots have the same Subject (so same Issuer for certs issued by them). So all roots are potential candidates. When we have >100 CAs in the trust bundle we hit that 100 signature checks limit and fail.

Getting into this situation depends a bit on number of spire-server instances, ca TTLs, upstream authorities. Those can be tuned a bit to avoid getting into this situation, but I don't think there's any way to guarantee you can avoid it. You're also likely to hit the issue in uncomfortable situations, e.g. scaling a deployment horizontally to deal with increased load. We should try to do something about it.

A way to fix it is to make sure that each self-signed CA issued by SPIRE has an unique Subject. For example it could include the serial number or some other attribute, similar to what has been done for X509-SVIDs in https://github.com/spiffe/spire/issues/3341. From what I can tell from that the X.509 RFC seems to be ok, there's no restriction on what the Subject of the CA needs to be.

* **Version**: 1.7.1 (but I guess that it applies for most/all older versions of SPIRE)
* **Platform**: any
* **Subsystem**: agent,server

### PR DESCRIPTION
**Pull request by sorindumitru**
This helps avoid running into a crypto/x509 limit that limits how many signature checks are allowed to happen to validate a certificate, most likely to avoid DoS attacks.

Building up a valid certificate chain is done based on the Subject field, even in the presence of an AKID. If all certificates from the bundle have the same Subject name, the verifier will attempt to build up a chain using all of them. Once we have more than 100 certificates in the bundle, we hit that crypto/x509 limit and start failing to verify X509-SVIDs.

Additionally this also improves mTLS channel establishment since we now no longer have to try to build a chain against all certificates from the bundle, we can easily identify the CA that signed an X509-SVID due to it having an unique Subject.

Example resulting Subject:
Subject: C = US, O = SPIFFE, serialNumber = 249778918434805435318471934298663515772

An experimental flag is also available to disable this feature in case there are issues encountered.

**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**
fixes #4415

### CODE REVIEW

File: cmd/spire-server/cli/run/run.go [hunk 1]
```diff
@@ -101,6 +101,8 @@ type experimentalConfig struct {
 	AuthOpaPolicyEngine  *authpolicy.OpaEngineConfig `hcl:"auth_opa_policy_engine"`
 	CacheReloadInterval  string                      `hcl:"cache_reload_interval"`
 	PruneEventsOlderThan string                      `hcl:"prune_events_older_than"`
+	// Temporary flag to allow disabling the inclusion of serial number in X509 CAs Subject field
+	ExcludeSNFromCASubject bool `hcl:"exclude_sn_from_ca_subject"`
```
Comment (azdagron) [inline cmd/spire-server/cli/run/run.go:105]: I think this should go in the non-experimental section of the config.

File: cmd/spire-server/cli/run/run.go [hunk 2]
```diff
@@ -668,6 +670,7 @@ func NewServerConfig(c *Config, logOptions []log.Option, allowUnknownConfig bool
 	}
 
 	sc.AuthOpaPolicyEngineConfig = c.Server.Experimental.AuthOpaPolicyEngine
+	sc.ExcludeSNFromCASubject = c.Server.Experimental.ExcludeSNFromCASubject
```
Comment (azdagron) [inline cmd/spire-server/cli/run/run.go:673]: Since we'd like to make this the default behavior, and are only including this temporary flag for one minor release for backcompat, I'd recommend adding some logging when this is set. Something like:
```
// TODO: remove exclude_sn_from_ca_subject in SPIRE v1.10.0
if sc.ExcludeSNFromCASubject {
	sc.Log.Warn("The deprecated exclude_sn_from_ca_subject configurable will be removed in a future release")
}
```

File: conf/server/server_full.conf [hunk 3]
```diff
@@ -33,6 +33,9 @@ server {
         common_name = ""
     }
 
+    # Temporary flag to allow disabling the inclusion of serial number in X509 CAs Subject field
+    exclude_sn_from_ca_subject = false
```
Comment (azdagron) [inline conf/server/server_full.conf:37]: nit: since `false` is the default value, this line should be commented

**Review by azdagron — APPROVED** [review]
LGTM! One nitpick in server_full.conf but it can be merged as-is.

**Review by azdagron — APPROVED** [review]
