### PR TITLE
Fix race conditions in rotator test

### LINKED ISSUE #2713: race detector makes TestRotator flaky in pkg/agent/svid
* **Version**: 20671191f75e52f3f698377dcca12325af87e6b3
* **Platform**: `Linux [redacted] 5.4.129+ #1 SMP Wed Aug 18 19:58:18 PDT 2021 x86_64 GNU/Linux`
* **Subsystem**: Agent

The `TestRotator` in `pkg/agent/svid` fails at an unacceptable frequency when run under the race detector. No specific data race is detected, but the additional overhead of enabling the race detector seems to trigger failures in some time-dependent tests. It tends to fail in one of 2 ways:

Example 1:
```
% go test -race -count 25 -failfast -run TestRotator ./pkg/agent/svid
--- FAIL: TestRotator (60.03s)
    --- FAIL: TestRotator/expires_after_startup (60.01s)
        rotator_test.go:113: timed out waiting for rotation check to finish after clock adjustment
FAIL
FAIL	github.com/spiffe/spire/pkg/agent/svid	60.486s
FAIL
```

Example 2:
```
% go test -race -count 25 -failfast -run TestRotator ./pkg/agent/svid
--- FAIL: TestRotator (0.07s)
    --- FAIL: TestRotator/expires_after_startup (0.03s)
        rotator_test.go:130:
            	Error Trace:	rotator_test.go:130
            	Error:      	Should be true
            	Test:       	TestRotator/expires_after_startup
            	Messages:   	SVID stream should have changes
FAIL
FAIL	github.com/spiffe/spire/pkg/agent/svid	0.135s
FAIL
```

These do not occur when race detector is not enabled:
```
% for i in $(seq 4)
do
    go test -count 25 -failfast -run TestRotator ./pkg/agent/svid
done
ok  	github.com/spiffe/spire/pkg/agent/svid	0.852s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.850s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.834s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.880s
```

### PR DESCRIPTION
**Pull request by mjlshen**
Signed-off-by: Michael Shen <mishen@umich.edu>

**Description of change**
Two test cases ran into race conditions as described in the issue, `not_expired_at_startup` and `expires_after_startup`

`not_expired_at_startup`
* The rotator sometimes shuts down with no error - this was puzzling to me as to why it circumvented the context cancellation, but adding a nil check fixed this (https://github.com/spiffe/spire/compare/main...mjlshen:rotator_race?expand=1#diff-2629a31628d2e08dceb05fa87836bc509d5410d142e61e1e69974aae1d485156R119-R121)

`expires_after_startup`
* By the time the initial rotation check happened, it was sometimes possible for the second rotation to already happen, causing a timeout while waiting for the supposed second rotation (actual third rotation) that will not happen for another hour. I fixed this by not even making an initial check, instead first incrementing the mock clock if needed and then checking for rotations/changes.

Misc fixes:
* The client variable was shadowing an imported `"github.com/spiffe/spire/pkg/agent/client"`, so I renamed it mockClient

**Which issue this PR fixes**
fixes #2713 

```
❯ uname -mrsv
Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

❯ for i in $(seq 10)
do
go test -race -count 25 -run TestRotator ./pkg/agent/svid
done
ok  	github.com/spiffe/spire/pkg/agent/svid	0.840s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.869s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.827s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.816s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.822s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.813s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.828s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.842s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.809s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.808s
```

### CODE REVIEW

File: pkg/agent/svid/rotator_test.go [hunk 1]
```diff
@@ -121,7 +116,9 @@ func TestRotator(t *testing.T) {
 			case <-time.After(time.Minute):
 				t.Fatal("timed out waiting for the rotator to shut down")
 			case err = <-errCh:
-				require.True(t, errors.Is(err, context.Canceled), "expected %v, not %v", context.Canceled, err)
+				if err != nil {
```
Comment (azdagron) [inline pkg/agent/svid/rotator_test.go:119]: I think we should probably change the rotator code to return ctx.Err() when the contexts are done though. The agent layer above this handles that and it makes for a more consistent return code, since RunTasks (used by Run) will return ctx.Err().

File: pkg/agent/svid/rotator_test.go [hunk 2]
```diff
@@ -73,7 +73,7 @@ func TestRotator(t *testing.T) {
 				SVID:           svid,
 				SVIDKey:        svidKey,
 			})
-			rotator.client = client
+			rotator.client = mockClient
```
Comment (azdagron) [inline pkg/agent/svid/rotator_test.go:76]: ❤️

File: pkg/agent/svid/rotator_test.go [hunk 3]
```diff
@@ -96,23 +96,18 @@ func TestRotator(t *testing.T) {
 				errCh <- rotator.Run(ctx)
 			}()
 
-			// Wait for the initial rotation check to finish
-			select {
-			case <-time.After(time.Minute):
-				t.Fatal("timed out waiting for rotation check to finish")
-			case <-rotationDone:
-			}
```
Comment (azdagron) [inline pkg/agent/svid/rotator_test.go:104]: I think we still need this lock-step in order for the tests to really assert the right things took place. What _is_ missing, and what fixes the race, is that we are not making sure that the rotator loop has made it back around and started waiting (via a select on r.clk.After) before we add time to the mock clock. I think adding adding a wait here for that After call fixes the race, while still keeping the right assertions in place.

```suggestion
			case <-rotationDone:
				clk.WaitForAfter(time.Minute, "waiting for rotation loop to start waiting")
```

**Review by azdagron — COMMENTED** [review]
Thank you @mjlshen for looking into this! I've made a few suggestions.

File: pkg/agent/svid/rotator_test.go (hunk 3 above)
Comment (mjlshen) [reply pkg/agent/svid/rotator_test.go]: Thanks for this suggestion! This clears up my confusion on how two runRotation loops could complete too.

Comment (mjlshen) [reply pkg/agent/svid/rotator_test.go]: One thing that this also made more obvious was a timing collision between `notAfter` and `checkAfter` in the "expires after startup" test case (https://github.com/spiffe/spire/pull/2738/files#diff-2629a31628d2e08dceb05fa87836bc509d5410d142e61e1e69974aae1d485156R50) which I fixed by adding one additional second to `checkAfter`

**Review by azdagron — APPROVED** [review]
Thanks for this, @mjlshen !
