### PR TITLE
[481] Let agent dialer do DNS resolution

### LINKED ISSUE #481: spire-agent can't recover via dns
spire-agent supports DNS-based lookup of server name, however the lookup is only done once, right as the agent is booting. As a result, if the server fails and is brought back at a different IP address, the agent can't recover. Similarly, if there are multiple spire servers, the agent will attach to one. If the one it attaches to fails, it can't recover.

Instead of doing DNS lookup at boot time, move the lookup as close to the dialer as possible. This way, if the underlying connection fails, we can perform another lookup.

https://github.com/spiffe/spire/blob/master/cmd/spire-agent/cli/run/run.go#L182-L194

### PR DESCRIPTION
**Pull request by evan2645**
In the beginning, spire-agent was configured with the IP address of
spire-server. As a quick win to support DNS names, a small step was
added to the command line package to perform a one-shot DNS resolution
if a name was supplied, and configure the agent with the first result.
Of course, this meant that if the name record was updated, we wouldn't
pick up the change.

The proposed solution was to move the resolution step closer to the
dialer. @marcosy contributed work in this direction (thank you
@marcosy!). While reviewing, I realized a few things:
* Agent was being configured with net.Addr so it could support other
transport types in the future with ease. We were using UDS transport in
the tests, but were otherwise maintaining this ability without actually
needing or using it right now
* net.Addr doesn't want DNS names
* Golang dialer actually implements the desired behavior - it will
resolve records on our behalf, and fall through the addresses if there
is more than one

Rather than continue to support net.Addr on the agent, which was forcing
us to handle DNS resolution on our own, I opted to back it out and go
for a host:port string instead. This now gets passed all the way down to
the dialer. TCP is now the hardcoded transport. If we need to support
others in the future, we can introduce additional Dialer methods.

Tested using HA mode in docker-compose, fixes #481.

### CODE REVIEW

File: pkg/agent/manager/manager_test.go [hunk 1]
```diff
@@ -155,10 +152,15 @@ func TestHappyPathWithoutSyncNorRotation(t *testing.T) {
 
 	trustDomain := "example.org"
 
+	l, err := net.Listen("tcp", "localhost:")
+	if err != nil {
+		t.Fatal(err)
+	}
+
```
Comment (azdagron) [inline pkg/agent/manager/manager_test.go]: defer l.Close()

File: cmd/spire-agent/cli/run/run.go [hunk 2]
```diff
@@ -180,23 +180,14 @@ func mergeConfigs(c *agent.Config, fileConfig, cliConfig *runConfig) error {
...
-			return err
-		}
-
-		if len(ips) == 0 {
-			return fmt.Errorf("Could not resolve ServerAddress %s", cmd.AgentConfig.ServerAddress)
-		}
-		serverAddress := ips[0]
-
-		orig.ServerAddress.IP = serverAddress
+		_, port, _ := net.SplitHostPort(orig.ServerAddress)
```
Comment (azdagron) [inline cmd/spire-agent/cli/run/run.go]: nit: we should maybe consider deprecating `ServerAddress` and `ServerPort` in lieu of a new `ServerHost` flag or something... I recognize that we don't want to break existing configs, but moving forward, it would be convenient and maybe clean up some of the processing code to have them specified in a single value.

Comment (azdagron) [reply cmd/spire-agent/cli/run/run.go]: Sounds reasonable.
